# Dockerfile References: https://docs.docker.com/engine/reference/builder/

# Start from the latest golang base image
FROM golang:latest as builder

WORKDIR /go/src/studiguide
RUN ls
COPY /back .
RUN go get
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -ldflags="-s" -o ../../bin/studiguide .



# --------------------- IONIC Build ------------------------
#FROM node:0.12

COPY /front /www/app

RUN npm install -g ionic

WORKDIR /www/app
RUN npm install

RUN ionic build --engine=browser


# blank container -------------------------------
FROM iron/base
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt

WORKDIR /go
COPY --from=builder go ./

# copy static files
WORKDIR /go/src/studiguide/static
RUN ls
COPY . /go/bin/static

WORKDIR /go/bin
RUN ls

# Expose port 8080 to the outside world
EXPOSE 8080

# Command to run the executable
CMD ["/go/bin/studiguide"]
