// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2020-03-31 15:46:40.981799087 +0200 CEST m=+0.130867510

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/map": {
            "get": {
                "description": "Gets all map items of available rooms and connector spaces (corridor, stairs, etc..)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "MapController"
                ],
                "summary": "Get All Map Items",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.MapItem"
                            }
                        }
                    }
                }
            }
        },
        "/map/floor": {
            "get": {
                "description": "Gets all map items of available rooms and connector spaces (corridor, stairs, etc..)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "MapController"
                ],
                "summary": "Get All Map Items",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "filter map items by floor",
                        "name": "floor",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.MapItem"
                            }
                        }
                    }
                }
            }
        },
        "/navigation/dir": {
            "get": {
                "description": "Gets the navigation route for a start and end room",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "NavigationController"
                ],
                "summary": "Get Navigation Route",
                "parameters": [
                    {
                        "type": "string",
                        "description": "the start room name",
                        "name": "startroom",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "the end room name",
                        "name": "endroom",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/navigation.Coordinate"
                            }
                        }
                    }
                }
            }
        },
        "/roomlist/": {
            "get": {
                "description": "Gets all available rooms",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "RoomController"
                ],
                "summary": "Get Room List",
                "operationId": "get-room-list",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Room"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.Door": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "pathNode": {
                    "type": "object",
                    "$ref": "#/definitions/navigation.PathNodes"
                },
                "section": {
                    "type": "object",
                    "$ref": "#/definitions/models.Section"
                }
            }
        },
        "models.MapItem": {
            "type": "object",
            "properties": {
                "alias": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "color": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "doors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Door"
                    }
                },
                "name": {
                    "type": "string"
                },
                "sections": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Section"
                    }
                }
            }
        },
        "models.Room": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "mapItem": {
                    "type": "object",
                    "$ref": "#/definitions/models.MapItem"
                },
                "pathNode": {
                    "type": "object",
                    "$ref": "#/definitions/navigation.PathNodes"
                }
            }
        },
        "models.Section": {
            "type": "object",
            "properties": {
                "end": {
                    "type": "object",
                    "$ref": "#/definitions/navigation.Coordinate"
                },
                "id": {
                    "type": "integer"
                },
                "start": {
                    "type": "object",
                    "$ref": "#/definitions/navigation.Coordinate"
                }
            }
        },
        "navigation.Coordinate": {
            "type": "object",
            "properties": {
                "x": {
                    "type": "integer"
                },
                "y": {
                    "type": "integer"
                },
                "z": {
                    "type": "integer"
                }
            }
        },
        "navigation.PathNodes": {
            "type": "object",
            "properties": {
                "coordinate": {
                    "type": "object",
                    "$ref": "#/definitions/navigation.Coordinate"
                },
                "group": {
                    "type": "object",
                    "$ref": "#/definitions/navigation.PathNodeGroup"
                },
                "id": {
                    "type": "integer"
                }
            }
        },
        "navigation.PathNodeGroup": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "nodes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/navigation.PathNodes"
                    }
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "",
	Host:        "",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "",
	Description: "",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
