// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// Door is the predicate function for door builders.
type Door func(*sql.Selector)

// PathNode is the predicate function for pathnode builders.
type PathNode func(*sql.Selector)

// Room is the predicate function for room builders.
type Room func(*sql.Selector)

// Sequence is the predicate function for sequence builders.
type Sequence func(*sql.Selector)
