// Code generated by entc, DO NOT EDIT.

package room

import (
	"studi-guide/ent/schema"
)

const (
	// Label holds the string label denoting the room type in the database.
	Label = "room"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name vertex property in the database.
	FieldName = "name"
	// FieldDescription holds the string denoting the description vertex property in the database.
	FieldDescription = "description"
	// FieldFloor holds the string denoting the floor vertex property in the database.
	FieldFloor = "floor"
	// FieldID holds the string denoting the id vertex property in the database.
	FieldID = "id"

	// Table holds the table name of the room in the database.
	Table = "rooms"
	// DoorsTable is the table the holds the doors relation/edge.
	DoorsTable = "doors"
	// DoorsInverseTable is the table name for the Door entity.
	// It exists in this package in order to avoid circular dependency with the "door" package.
	DoorsInverseTable = "doors"
	// DoorsColumn is the table column denoting the doors relation/edge.
	DoorsColumn = "room_doors"
	// SequencesTable is the table the holds the sequences relation/edge.
	SequencesTable = "sequences"
	// SequencesInverseTable is the table name for the Sequence entity.
	// It exists in this package in order to avoid circular dependency with the "sequence" package.
	SequencesInverseTable = "sequences"
	// SequencesColumn is the table column denoting the sequences relation/edge.
	SequencesColumn = "room_sequences"
	// PathNodesTable is the table the holds the pathNodes relation/edge.
	PathNodesTable = "path_nodes"
	// PathNodesInverseTable is the table name for the PathNode entity.
	// It exists in this package in order to avoid circular dependency with the "pathnode" package.
	PathNodesInverseTable = "path_nodes"
	// PathNodesColumn is the table column denoting the pathNodes relation/edge.
	PathNodesColumn = "room_path_nodes"
)

// Columns holds all SQL columns for room fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldDescription,
	FieldFloor,
	FieldID,
}

var (
	fields = schema.Room{}.Fields()

	// descDescription is the schema descriptor for Description field.
	descDescription = fields[1].Descriptor()
	// DefaultDescription holds the default value on creation for the Description field.
	DefaultDescription = descDescription.Default.(string)

	// descFloor is the schema descriptor for Floor field.
	descFloor = fields[2].Descriptor()
	// DefaultFloor holds the default value on creation for the Floor field.
	DefaultFloor = descFloor.Default.(int)
)
