// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"log"

	"studi-guide/ent/migrate"

	"studi-guide/ent/door"
	"studi-guide/ent/pathnode"
	"studi-guide/ent/room"
	"studi-guide/ent/sequence"

	"github.com/facebookincubator/ent/dialect"
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Door is the client for interacting with the Door builders.
	Door *DoorClient
	// PathNode is the client for interacting with the PathNode builders.
	PathNode *PathNodeClient
	// Room is the client for interacting with the Room builders.
	Room *RoomClient
	// Sequence is the client for interacting with the Sequence builders.
	Sequence *SequenceClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	c := config{log: log.Println}
	c.options(opts...)
	return &Client{
		config:   c,
		Schema:   migrate.NewSchema(c.driver),
		Door:     NewDoorClient(c),
		PathNode: NewPathNodeClient(c),
		Room:     NewRoomClient(c),
		Sequence: NewSequenceClient(c),
	}
}

// Open opens a connection to the database specified by the driver name and a
// driver-specific data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// Tx returns a new transactional client.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %v", err)
	}
	cfg := config{driver: tx, log: c.log, debug: c.debug}
	return &Tx{
		config:   cfg,
		Door:     NewDoorClient(cfg),
		PathNode: NewPathNodeClient(cfg),
		Room:     NewRoomClient(cfg),
		Sequence: NewSequenceClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Door.
//		Query().
//		Count(ctx)
//
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := config{driver: dialect.Debug(c.driver, c.log), log: c.log, debug: true}
	return &Client{
		config:   cfg,
		Schema:   migrate.NewSchema(cfg.driver),
		Door:     NewDoorClient(cfg),
		PathNode: NewPathNodeClient(cfg),
		Room:     NewRoomClient(cfg),
		Sequence: NewSequenceClient(cfg),
	}
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// DoorClient is a client for the Door schema.
type DoorClient struct {
	config
}

// NewDoorClient returns a client for the Door from the given config.
func NewDoorClient(c config) *DoorClient {
	return &DoorClient{config: c}
}

// Create returns a create builder for Door.
func (c *DoorClient) Create() *DoorCreate {
	return &DoorCreate{config: c.config}
}

// Update returns an update builder for Door.
func (c *DoorClient) Update() *DoorUpdate {
	return &DoorUpdate{config: c.config}
}

// UpdateOne returns an update builder for the given entity.
func (c *DoorClient) UpdateOne(d *Door) *DoorUpdateOne {
	return c.UpdateOneID(d.ID)
}

// UpdateOneID returns an update builder for the given id.
func (c *DoorClient) UpdateOneID(id int) *DoorUpdateOne {
	return &DoorUpdateOne{config: c.config, id: id}
}

// Delete returns a delete builder for Door.
func (c *DoorClient) Delete() *DoorDelete {
	return &DoorDelete{config: c.config}
}

// DeleteOne returns a delete builder for the given entity.
func (c *DoorClient) DeleteOne(d *Door) *DoorDeleteOne {
	return c.DeleteOneID(d.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *DoorClient) DeleteOneID(id int) *DoorDeleteOne {
	return &DoorDeleteOne{c.Delete().Where(door.ID(id))}
}

// Create returns a query builder for Door.
func (c *DoorClient) Query() *DoorQuery {
	return &DoorQuery{config: c.config}
}

// Get returns a Door entity by its id.
func (c *DoorClient) Get(ctx context.Context, id int) (*Door, error) {
	return c.Query().Where(door.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *DoorClient) GetX(ctx context.Context, id int) *Door {
	d, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return d
}

// QuerySequence queries the sequence edge of a Door.
func (c *DoorClient) QuerySequence(d *Door) *SequenceQuery {
	query := &SequenceQuery{config: c.config}
	id := d.ID
	step := sqlgraph.NewStep(
		sqlgraph.From(door.Table, door.FieldID, id),
		sqlgraph.To(sequence.Table, sequence.FieldID),
		sqlgraph.Edge(sqlgraph.O2O, false, door.SequenceTable, door.SequenceColumn),
	)
	query.sql = sqlgraph.Neighbors(d.driver.Dialect(), step)

	return query
}

// QueryPathNodes queries the pathNodes edge of a Door.
func (c *DoorClient) QueryPathNodes(d *Door) *PathNodeQuery {
	query := &PathNodeQuery{config: c.config}
	id := d.ID
	step := sqlgraph.NewStep(
		sqlgraph.From(door.Table, door.FieldID, id),
		sqlgraph.To(pathnode.Table, pathnode.FieldID),
		sqlgraph.Edge(sqlgraph.O2O, false, door.PathNodesTable, door.PathNodesColumn),
	)
	query.sql = sqlgraph.Neighbors(d.driver.Dialect(), step)

	return query
}

// PathNodeClient is a client for the PathNode schema.
type PathNodeClient struct {
	config
}

// NewPathNodeClient returns a client for the PathNode from the given config.
func NewPathNodeClient(c config) *PathNodeClient {
	return &PathNodeClient{config: c}
}

// Create returns a create builder for PathNode.
func (c *PathNodeClient) Create() *PathNodeCreate {
	return &PathNodeCreate{config: c.config}
}

// Update returns an update builder for PathNode.
func (c *PathNodeClient) Update() *PathNodeUpdate {
	return &PathNodeUpdate{config: c.config}
}

// UpdateOne returns an update builder for the given entity.
func (c *PathNodeClient) UpdateOne(pn *PathNode) *PathNodeUpdateOne {
	return c.UpdateOneID(pn.ID)
}

// UpdateOneID returns an update builder for the given id.
func (c *PathNodeClient) UpdateOneID(id int) *PathNodeUpdateOne {
	return &PathNodeUpdateOne{config: c.config, id: id}
}

// Delete returns a delete builder for PathNode.
func (c *PathNodeClient) Delete() *PathNodeDelete {
	return &PathNodeDelete{config: c.config}
}

// DeleteOne returns a delete builder for the given entity.
func (c *PathNodeClient) DeleteOne(pn *PathNode) *PathNodeDeleteOne {
	return c.DeleteOneID(pn.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *PathNodeClient) DeleteOneID(id int) *PathNodeDeleteOne {
	return &PathNodeDeleteOne{c.Delete().Where(pathnode.ID(id))}
}

// Create returns a query builder for PathNode.
func (c *PathNodeClient) Query() *PathNodeQuery {
	return &PathNodeQuery{config: c.config}
}

// Get returns a PathNode entity by its id.
func (c *PathNodeClient) Get(ctx context.Context, id int) (*PathNode, error) {
	return c.Query().Where(pathnode.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *PathNodeClient) GetX(ctx context.Context, id int) *PathNode {
	pn, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return pn
}

// QueryDoor queries the door edge of a PathNode.
func (c *PathNodeClient) QueryDoor(pn *PathNode) *DoorQuery {
	query := &DoorQuery{config: c.config}
	id := pn.ID
	step := sqlgraph.NewStep(
		sqlgraph.From(pathnode.Table, pathnode.FieldID, id),
		sqlgraph.To(door.Table, door.FieldID),
		sqlgraph.Edge(sqlgraph.O2O, true, pathnode.DoorTable, pathnode.DoorColumn),
	)
	query.sql = sqlgraph.Neighbors(pn.driver.Dialect(), step)

	return query
}

// QueryRoom queries the room edge of a PathNode.
func (c *PathNodeClient) QueryRoom(pn *PathNode) *RoomQuery {
	query := &RoomQuery{config: c.config}
	id := pn.ID
	step := sqlgraph.NewStep(
		sqlgraph.From(pathnode.Table, pathnode.FieldID, id),
		sqlgraph.To(room.Table, room.FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, pathnode.RoomTable, pathnode.RoomColumn),
	)
	query.sql = sqlgraph.Neighbors(pn.driver.Dialect(), step)

	return query
}

// QueryLinkedFrom queries the linkedFrom edge of a PathNode.
func (c *PathNodeClient) QueryLinkedFrom(pn *PathNode) *PathNodeQuery {
	query := &PathNodeQuery{config: c.config}
	id := pn.ID
	step := sqlgraph.NewStep(
		sqlgraph.From(pathnode.Table, pathnode.FieldID, id),
		sqlgraph.To(pathnode.Table, pathnode.FieldID),
		sqlgraph.Edge(sqlgraph.M2M, true, pathnode.LinkedFromTable, pathnode.LinkedFromPrimaryKey...),
	)
	query.sql = sqlgraph.Neighbors(pn.driver.Dialect(), step)

	return query
}

// QueryLinkedTo queries the linkedTo edge of a PathNode.
func (c *PathNodeClient) QueryLinkedTo(pn *PathNode) *PathNodeQuery {
	query := &PathNodeQuery{config: c.config}
	id := pn.ID
	step := sqlgraph.NewStep(
		sqlgraph.From(pathnode.Table, pathnode.FieldID, id),
		sqlgraph.To(pathnode.Table, pathnode.FieldID),
		sqlgraph.Edge(sqlgraph.M2M, false, pathnode.LinkedToTable, pathnode.LinkedToPrimaryKey...),
	)
	query.sql = sqlgraph.Neighbors(pn.driver.Dialect(), step)

	return query
}

// RoomClient is a client for the Room schema.
type RoomClient struct {
	config
}

// NewRoomClient returns a client for the Room from the given config.
func NewRoomClient(c config) *RoomClient {
	return &RoomClient{config: c}
}

// Create returns a create builder for Room.
func (c *RoomClient) Create() *RoomCreate {
	return &RoomCreate{config: c.config}
}

// Update returns an update builder for Room.
func (c *RoomClient) Update() *RoomUpdate {
	return &RoomUpdate{config: c.config}
}

// UpdateOne returns an update builder for the given entity.
func (c *RoomClient) UpdateOne(r *Room) *RoomUpdateOne {
	return c.UpdateOneID(r.ID)
}

// UpdateOneID returns an update builder for the given id.
func (c *RoomClient) UpdateOneID(id int) *RoomUpdateOne {
	return &RoomUpdateOne{config: c.config, id: id}
}

// Delete returns a delete builder for Room.
func (c *RoomClient) Delete() *RoomDelete {
	return &RoomDelete{config: c.config}
}

// DeleteOne returns a delete builder for the given entity.
func (c *RoomClient) DeleteOne(r *Room) *RoomDeleteOne {
	return c.DeleteOneID(r.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *RoomClient) DeleteOneID(id int) *RoomDeleteOne {
	return &RoomDeleteOne{c.Delete().Where(room.ID(id))}
}

// Create returns a query builder for Room.
func (c *RoomClient) Query() *RoomQuery {
	return &RoomQuery{config: c.config}
}

// Get returns a Room entity by its id.
func (c *RoomClient) Get(ctx context.Context, id int) (*Room, error) {
	return c.Query().Where(room.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *RoomClient) GetX(ctx context.Context, id int) *Room {
	r, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return r
}

// QueryDoors queries the doors edge of a Room.
func (c *RoomClient) QueryDoors(r *Room) *DoorQuery {
	query := &DoorQuery{config: c.config}
	id := r.ID
	step := sqlgraph.NewStep(
		sqlgraph.From(room.Table, room.FieldID, id),
		sqlgraph.To(door.Table, door.FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, room.DoorsTable, room.DoorsColumn),
	)
	query.sql = sqlgraph.Neighbors(r.driver.Dialect(), step)

	return query
}

// QuerySequences queries the sequences edge of a Room.
func (c *RoomClient) QuerySequences(r *Room) *SequenceQuery {
	query := &SequenceQuery{config: c.config}
	id := r.ID
	step := sqlgraph.NewStep(
		sqlgraph.From(room.Table, room.FieldID, id),
		sqlgraph.To(sequence.Table, sequence.FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, room.SequencesTable, room.SequencesColumn),
	)
	query.sql = sqlgraph.Neighbors(r.driver.Dialect(), step)

	return query
}

// QueryPathNodes queries the pathNodes edge of a Room.
func (c *RoomClient) QueryPathNodes(r *Room) *PathNodeQuery {
	query := &PathNodeQuery{config: c.config}
	id := r.ID
	step := sqlgraph.NewStep(
		sqlgraph.From(room.Table, room.FieldID, id),
		sqlgraph.To(pathnode.Table, pathnode.FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, room.PathNodesTable, room.PathNodesColumn),
	)
	query.sql = sqlgraph.Neighbors(r.driver.Dialect(), step)

	return query
}

// SequenceClient is a client for the Sequence schema.
type SequenceClient struct {
	config
}

// NewSequenceClient returns a client for the Sequence from the given config.
func NewSequenceClient(c config) *SequenceClient {
	return &SequenceClient{config: c}
}

// Create returns a create builder for Sequence.
func (c *SequenceClient) Create() *SequenceCreate {
	return &SequenceCreate{config: c.config}
}

// Update returns an update builder for Sequence.
func (c *SequenceClient) Update() *SequenceUpdate {
	return &SequenceUpdate{config: c.config}
}

// UpdateOne returns an update builder for the given entity.
func (c *SequenceClient) UpdateOne(s *Sequence) *SequenceUpdateOne {
	return c.UpdateOneID(s.ID)
}

// UpdateOneID returns an update builder for the given id.
func (c *SequenceClient) UpdateOneID(id int) *SequenceUpdateOne {
	return &SequenceUpdateOne{config: c.config, id: id}
}

// Delete returns a delete builder for Sequence.
func (c *SequenceClient) Delete() *SequenceDelete {
	return &SequenceDelete{config: c.config}
}

// DeleteOne returns a delete builder for the given entity.
func (c *SequenceClient) DeleteOne(s *Sequence) *SequenceDeleteOne {
	return c.DeleteOneID(s.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *SequenceClient) DeleteOneID(id int) *SequenceDeleteOne {
	return &SequenceDeleteOne{c.Delete().Where(sequence.ID(id))}
}

// Create returns a query builder for Sequence.
func (c *SequenceClient) Query() *SequenceQuery {
	return &SequenceQuery{config: c.config}
}

// Get returns a Sequence entity by its id.
func (c *SequenceClient) Get(ctx context.Context, id int) (*Sequence, error) {
	return c.Query().Where(sequence.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *SequenceClient) GetX(ctx context.Context, id int) *Sequence {
	s, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return s
}

// QueryDoor queries the door edge of a Sequence.
func (c *SequenceClient) QueryDoor(s *Sequence) *DoorQuery {
	query := &DoorQuery{config: c.config}
	id := s.ID
	step := sqlgraph.NewStep(
		sqlgraph.From(sequence.Table, sequence.FieldID, id),
		sqlgraph.To(door.Table, door.FieldID),
		sqlgraph.Edge(sqlgraph.O2O, true, sequence.DoorTable, sequence.DoorColumn),
	)
	query.sql = sqlgraph.Neighbors(s.driver.Dialect(), step)

	return query
}

// QueryRoom queries the room edge of a Sequence.
func (c *SequenceClient) QueryRoom(s *Sequence) *RoomQuery {
	query := &RoomQuery{config: c.config}
	id := s.ID
	step := sqlgraph.NewStep(
		sqlgraph.From(sequence.Table, sequence.FieldID, id),
		sqlgraph.To(room.Table, room.FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, sequence.RoomTable, sequence.RoomColumn),
	)
	query.sql = sqlgraph.Neighbors(s.driver.Dialect(), step)

	return query
}
