// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"studi-guide/ent/door"
	"studi-guide/ent/pathnode"
	"studi-guide/ent/sequence"

	"github.com/facebookincubator/ent/dialect/sql"
)

// Door is the model entity for the Door schema.
type Door struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// ID holds the value of the "Id" field.
	ID int `json:"Id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the DoorQuery when eager-loading is set.
	Edges      DoorEdges `json:"edges"`
	room_doors *int
}

// DoorEdges holds the relations/edges for other nodes in the graph.
type DoorEdges struct {
	// Sequence holds the value of the sequence edge.
	Sequence *Sequence
	// PathNodes holds the value of the pathNodes edge.
	PathNodes *PathNode
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// SequenceOrErr returns the Sequence value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e DoorEdges) SequenceOrErr() (*Sequence, error) {
	if e.loadedTypes[0] {
		if e.Sequence == nil {
			// The edge sequence was loaded in eager-loading,
			// but was not found.
			return nil, &NotFoundError{label: sequence.Label}
		}
		return e.Sequence, nil
	}
	return nil, &NotLoadedError{edge: "sequence"}
}

// PathNodesOrErr returns the PathNodes value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e DoorEdges) PathNodesOrErr() (*PathNode, error) {
	if e.loadedTypes[1] {
		if e.PathNodes == nil {
			// The edge pathNodes was loaded in eager-loading,
			// but was not found.
			return nil, &NotFoundError{label: pathnode.Label}
		}
		return e.PathNodes, nil
	}
	return nil, &NotLoadedError{edge: "pathNodes"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Door) scanValues() []interface{} {
	return []interface{}{
		&sql.NullInt64{}, // id
		&sql.NullInt64{}, // Id
	}
}

// fkValues returns the types for scanning foreign-keys values from sql.Rows.
func (*Door) fkValues() []interface{} {
	return []interface{}{
		&sql.NullInt64{}, // room_doors
	}
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Door fields.
func (d *Door) assignValues(values ...interface{}) error {
	if m, n := len(values), len(door.Columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	value, ok := values[0].(*sql.NullInt64)
	if !ok {
		return fmt.Errorf("unexpected type %T for field id", value)
	}
	d.ID = int(value.Int64)
	values = values[1:]
	if value, ok := values[0].(*sql.NullInt64); !ok {
		return fmt.Errorf("unexpected type %T for field Id", values[0])
	} else if value.Valid {
		d.ID = int(value.Int64)
	}
	values = values[1:]
	if len(values) == len(door.ForeignKeys) {
		if value, ok := values[0].(*sql.NullInt64); !ok {
			return fmt.Errorf("unexpected type %T for edge-field room_doors", value)
		} else if value.Valid {
			d.room_doors = new(int)
			*d.room_doors = int(value.Int64)
		}
	}
	return nil
}

// QuerySequence queries the sequence edge of the Door.
func (d *Door) QuerySequence() *SequenceQuery {
	return (&DoorClient{d.config}).QuerySequence(d)
}

// QueryPathNodes queries the pathNodes edge of the Door.
func (d *Door) QueryPathNodes() *PathNodeQuery {
	return (&DoorClient{d.config}).QueryPathNodes(d)
}

// Update returns a builder for updating this Door.
// Note that, you need to call Door.Unwrap() before calling this method, if this Door
// was returned from a transaction, and the transaction was committed or rolled back.
func (d *Door) Update() *DoorUpdateOne {
	return (&DoorClient{d.config}).UpdateOne(d)
}

// Unwrap unwraps the entity that was returned from a transaction after it was closed,
// so that all next queries will be executed through the driver which created the transaction.
func (d *Door) Unwrap() *Door {
	tx, ok := d.config.driver.(*txDriver)
	if !ok {
		panic("ent: Door is not a transactional entity")
	}
	d.config.driver = tx.drv
	return d
}

// String implements the fmt.Stringer.
func (d *Door) String() string {
	var builder strings.Builder
	builder.WriteString("Door(")
	builder.WriteString(fmt.Sprintf("id=%v", d.ID))
	builder.WriteString(", Id=")
	builder.WriteString(fmt.Sprintf("%v", d.ID))
	builder.WriteByte(')')
	return builder.String()
}

// Doors is a parsable slice of Door.
type Doors []*Door

func (d Doors) config(cfg config) {
	for _i := range d {
		d[_i].config = cfg
	}
}
