// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"studi-guide/ent/door"
	"studi-guide/ent/pathnode"
	"studi-guide/ent/sequence"

	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// DoorCreate is the builder for creating a Door entity.
type DoorCreate struct {
	config
	Id        *int
	sequence  map[int]struct{}
	pathNodes map[int]struct{}
}

// SetID sets the Id field.
func (dc *DoorCreate) SetID(i int) *DoorCreate {
	dc.Id = &i
	return dc
}

// SetSequenceID sets the sequence edge to Sequence by id.
func (dc *DoorCreate) SetSequenceID(id int) *DoorCreate {
	if dc.sequence == nil {
		dc.sequence = make(map[int]struct{})
	}
	dc.sequence[id] = struct{}{}
	return dc
}

// SetNillableSequenceID sets the sequence edge to Sequence by id if the given value is not nil.
func (dc *DoorCreate) SetNillableSequenceID(id *int) *DoorCreate {
	if id != nil {
		dc = dc.SetSequenceID(*id)
	}
	return dc
}

// SetSequence sets the sequence edge to Sequence.
func (dc *DoorCreate) SetSequence(s *Sequence) *DoorCreate {
	return dc.SetSequenceID(s.ID)
}

// SetPathNodesID sets the pathNodes edge to PathNode by id.
func (dc *DoorCreate) SetPathNodesID(id int) *DoorCreate {
	if dc.pathNodes == nil {
		dc.pathNodes = make(map[int]struct{})
	}
	dc.pathNodes[id] = struct{}{}
	return dc
}

// SetNillablePathNodesID sets the pathNodes edge to PathNode by id if the given value is not nil.
func (dc *DoorCreate) SetNillablePathNodesID(id *int) *DoorCreate {
	if id != nil {
		dc = dc.SetPathNodesID(*id)
	}
	return dc
}

// SetPathNodes sets the pathNodes edge to PathNode.
func (dc *DoorCreate) SetPathNodes(p *PathNode) *DoorCreate {
	return dc.SetPathNodesID(p.ID)
}

// Save creates the Door in the database.
func (dc *DoorCreate) Save(ctx context.Context) (*Door, error) {
	if dc.Id == nil {
		return nil, errors.New("ent: missing required field \"Id\"")
	}
	if len(dc.sequence) > 1 {
		return nil, errors.New("ent: multiple assignments on a unique edge \"sequence\"")
	}
	if len(dc.pathNodes) > 1 {
		return nil, errors.New("ent: multiple assignments on a unique edge \"pathNodes\"")
	}
	return dc.sqlSave(ctx)
}

// SaveX calls Save and panics if Save returns an error.
func (dc *DoorCreate) SaveX(ctx context.Context) *Door {
	v, err := dc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (dc *DoorCreate) sqlSave(ctx context.Context) (*Door, error) {
	var (
		d     = &Door{config: dc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: door.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: door.FieldID,
			},
		}
	)
	if value := dc.Id; value != nil {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  *value,
			Column: door.FieldID,
		})
		d.ID = *value
	}
	if nodes := dc.sequence; len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   door.SequenceTable,
			Columns: []string{door.SequenceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: sequence.FieldID,
				},
			},
		}
		for k, _ := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := dc.pathNodes; len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   door.PathNodesTable,
			Columns: []string{door.PathNodesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: pathnode.FieldID,
				},
			},
		}
		for k, _ := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if err := sqlgraph.CreateNode(ctx, dc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	d.ID = int(id)
	return d, nil
}
