// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"studi-guide/ent/door"
	"studi-guide/ent/predicate"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// DoorDelete is the builder for deleting a Door entity.
type DoorDelete struct {
	config
	predicates []predicate.Door
}

// Where adds a new predicate to the delete builder.
func (dd *DoorDelete) Where(ps ...predicate.Door) *DoorDelete {
	dd.predicates = append(dd.predicates, ps...)
	return dd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (dd *DoorDelete) Exec(ctx context.Context) (int, error) {
	return dd.sqlExec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (dd *DoorDelete) ExecX(ctx context.Context) int {
	n, err := dd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (dd *DoorDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: door.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: door.FieldID,
			},
		},
	}
	if ps := dd.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, dd.driver, _spec)
}

// DoorDeleteOne is the builder for deleting a single Door entity.
type DoorDeleteOne struct {
	dd *DoorDelete
}

// Exec executes the deletion query.
func (ddo *DoorDeleteOne) Exec(ctx context.Context) error {
	n, err := ddo.dd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{door.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ddo *DoorDeleteOne) ExecX(ctx context.Context) {
	ddo.dd.ExecX(ctx)
}
