// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"log"

	"github.com/facebookincubator/ent/dialect/sql"
)

// dsn for the database. In order to run the tests locally, run the following command:
//
//	 ENT_INTEGRATION_ENDPOINT="root:pass@tcp(localhost:3306)/test?parseTime=True" go test -v
//
var dsn string

func ExampleDoor() {
	if dsn == "" {
		return
	}
	ctx := context.Background()
	drv, err := sql.Open("mysql", dsn)
	if err != nil {
		log.Fatalf("failed creating database client: %v", err)
	}
	defer drv.Close()
	client := NewClient(Driver(drv))
	// creating vertices for the door's edges.
	s0 := client.Sequence.
		Create().
		SetXStart(1).
		SetYStart(1).
		SetXEnd(1).
		SetYEnd(1).
		SaveX(ctx)
	log.Println("sequence created:", s0)
	pn1 := client.PathNode.
		Create().
		SetXCoordinate(1).
		SetYCoordinate(1).
		SetFloor(1).
		SaveX(ctx)
	log.Println("pathnode created:", pn1)

	// create door vertex with its edges.
	d := client.Door.
		Create().
		SetSequence(s0).
		SetPathNodes(pn1).
		SaveX(ctx)
	log.Println("door created:", d)

	// query edges.
	s0, err = d.QuerySequence().First(ctx)
	if err != nil {
		log.Fatalf("failed querying sequence: %v", err)
	}
	log.Println("sequence found:", s0)

	pn1, err = d.QueryPathNodes().First(ctx)
	if err != nil {
		log.Fatalf("failed querying pathNodes: %v", err)
	}
	log.Println("pathNodes found:", pn1)

	// Output:
}
func ExamplePathNode() {
	if dsn == "" {
		return
	}
	ctx := context.Background()
	drv, err := sql.Open("mysql", dsn)
	if err != nil {
		log.Fatalf("failed creating database client: %v", err)
	}
	defer drv.Close()
	client := NewClient(Driver(drv))
	// creating vertices for the pathnode's edges.
	pn3 := client.PathNode.
		Create().
		SetXCoordinate(1).
		SetYCoordinate(1).
		SetFloor(1).
		SaveX(ctx)
	log.Println("pathnode created:", pn3)

	// create pathnode vertex with its edges.
	pn := client.PathNode.
		Create().
		SetXCoordinate(1).
		SetYCoordinate(1).
		SetFloor(1).
		AddLinkedTo(pn3).
		SaveX(ctx)
	log.Println("pathnode created:", pn)

	// query edges.

	pn3, err = pn.QueryLinkedTo().First(ctx)
	if err != nil {
		log.Fatalf("failed querying linkedTo: %v", err)
	}
	log.Println("linkedTo found:", pn3)

	// Output:
}
func ExampleRoom() {
	if dsn == "" {
		return
	}
	ctx := context.Background()
	drv, err := sql.Open("mysql", dsn)
	if err != nil {
		log.Fatalf("failed creating database client: %v", err)
	}
	defer drv.Close()
	client := NewClient(Driver(drv))
	// creating vertices for the room's edges.
	d0 := client.Door.
		Create().
		SaveX(ctx)
	log.Println("door created:", d0)
	s1 := client.Sequence.
		Create().
		SetXStart(1).
		SetYStart(1).
		SetXEnd(1).
		SetYEnd(1).
		SaveX(ctx)
	log.Println("sequence created:", s1)
	pn2 := client.PathNode.
		Create().
		SetXCoordinate(1).
		SetYCoordinate(1).
		SetFloor(1).
		SaveX(ctx)
	log.Println("pathnode created:", pn2)

	// create room vertex with its edges.
	r := client.Room.
		Create().
		SetName("string").
		SetDescription("string").
		SetFloor(1).
		AddDoors(d0).
		AddSequences(s1).
		AddPathNodes(pn2).
		SaveX(ctx)
	log.Println("room created:", r)

	// query edges.
	d0, err = r.QueryDoors().First(ctx)
	if err != nil {
		log.Fatalf("failed querying doors: %v", err)
	}
	log.Println("doors found:", d0)

	s1, err = r.QuerySequences().First(ctx)
	if err != nil {
		log.Fatalf("failed querying sequences: %v", err)
	}
	log.Println("sequences found:", s1)

	pn2, err = r.QueryPathNodes().First(ctx)
	if err != nil {
		log.Fatalf("failed querying pathNodes: %v", err)
	}
	log.Println("pathNodes found:", pn2)

	// Output:
}
func ExampleSequence() {
	if dsn == "" {
		return
	}
	ctx := context.Background()
	drv, err := sql.Open("mysql", dsn)
	if err != nil {
		log.Fatalf("failed creating database client: %v", err)
	}
	defer drv.Close()
	client := NewClient(Driver(drv))
	// creating vertices for the sequence's edges.

	// create sequence vertex with its edges.
	s := client.Sequence.
		Create().
		SetXStart(1).
		SetYStart(1).
		SetXEnd(1).
		SetYEnd(1).
		SaveX(ctx)
	log.Println("sequence created:", s)

	// query edges.

	// Output:
}
