// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"studi-guide/ent/door"
	"studi-guide/ent/pathnode"
	"studi-guide/ent/room"

	"github.com/facebookincubator/ent/dialect/sql"
)

// PathNode is the model entity for the PathNode schema.
type PathNode struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// ID holds the value of the "Id" field.
	ID int `json:"Id,omitempty"`
	// XCoordinate holds the value of the "X_Coordinate" field.
	XCoordinate int `json:"X_Coordinate,omitempty"`
	// YCoordinate holds the value of the "Y_Coordinate" field.
	YCoordinate int `json:"Y_Coordinate,omitempty"`
	// Floor holds the value of the "Floor" field.
	Floor int `json:"Floor,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PathNodeQuery when eager-loading is set.
	Edges           PathNodeEdges `json:"edges"`
	door_path_nodes *int
	room_path_nodes *int
}

// PathNodeEdges holds the relations/edges for other nodes in the graph.
type PathNodeEdges struct {
	// Door holds the value of the door edge.
	Door *Door
	// Room holds the value of the room edge.
	Room *Room
	// LinkedFrom holds the value of the linkedFrom edge.
	LinkedFrom []*PathNode
	// LinkedTo holds the value of the linkedTo edge.
	LinkedTo []*PathNode
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [4]bool
}

// DoorOrErr returns the Door value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PathNodeEdges) DoorOrErr() (*Door, error) {
	if e.loadedTypes[0] {
		if e.Door == nil {
			// The edge door was loaded in eager-loading,
			// but was not found.
			return nil, &NotFoundError{label: door.Label}
		}
		return e.Door, nil
	}
	return nil, &NotLoadedError{edge: "door"}
}

// RoomOrErr returns the Room value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PathNodeEdges) RoomOrErr() (*Room, error) {
	if e.loadedTypes[1] {
		if e.Room == nil {
			// The edge room was loaded in eager-loading,
			// but was not found.
			return nil, &NotFoundError{label: room.Label}
		}
		return e.Room, nil
	}
	return nil, &NotLoadedError{edge: "room"}
}

// LinkedFromOrErr returns the LinkedFrom value or an error if the edge
// was not loaded in eager-loading.
func (e PathNodeEdges) LinkedFromOrErr() ([]*PathNode, error) {
	if e.loadedTypes[2] {
		return e.LinkedFrom, nil
	}
	return nil, &NotLoadedError{edge: "linkedFrom"}
}

// LinkedToOrErr returns the LinkedTo value or an error if the edge
// was not loaded in eager-loading.
func (e PathNodeEdges) LinkedToOrErr() ([]*PathNode, error) {
	if e.loadedTypes[3] {
		return e.LinkedTo, nil
	}
	return nil, &NotLoadedError{edge: "linkedTo"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PathNode) scanValues() []interface{} {
	return []interface{}{
		&sql.NullInt64{}, // id
		&sql.NullInt64{}, // Id
		&sql.NullInt64{}, // X_Coordinate
		&sql.NullInt64{}, // Y_Coordinate
		&sql.NullInt64{}, // Floor
	}
}

// fkValues returns the types for scanning foreign-keys values from sql.Rows.
func (*PathNode) fkValues() []interface{} {
	return []interface{}{
		&sql.NullInt64{}, // door_path_nodes
		&sql.NullInt64{}, // room_path_nodes
	}
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PathNode fields.
func (pn *PathNode) assignValues(values ...interface{}) error {
	if m, n := len(values), len(pathnode.Columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	value, ok := values[0].(*sql.NullInt64)
	if !ok {
		return fmt.Errorf("unexpected type %T for field id", value)
	}
	pn.ID = int(value.Int64)
	values = values[1:]
	if value, ok := values[0].(*sql.NullInt64); !ok {
		return fmt.Errorf("unexpected type %T for field Id", values[0])
	} else if value.Valid {
		pn.ID = int(value.Int64)
	}
	if value, ok := values[1].(*sql.NullInt64); !ok {
		return fmt.Errorf("unexpected type %T for field X_Coordinate", values[1])
	} else if value.Valid {
		pn.XCoordinate = int(value.Int64)
	}
	if value, ok := values[2].(*sql.NullInt64); !ok {
		return fmt.Errorf("unexpected type %T for field Y_Coordinate", values[2])
	} else if value.Valid {
		pn.YCoordinate = int(value.Int64)
	}
	if value, ok := values[3].(*sql.NullInt64); !ok {
		return fmt.Errorf("unexpected type %T for field Floor", values[3])
	} else if value.Valid {
		pn.Floor = int(value.Int64)
	}
	values = values[4:]
	if len(values) == len(pathnode.ForeignKeys) {
		if value, ok := values[0].(*sql.NullInt64); !ok {
			return fmt.Errorf("unexpected type %T for edge-field door_path_nodes", value)
		} else if value.Valid {
			pn.door_path_nodes = new(int)
			*pn.door_path_nodes = int(value.Int64)
		}
		if value, ok := values[1].(*sql.NullInt64); !ok {
			return fmt.Errorf("unexpected type %T for edge-field room_path_nodes", value)
		} else if value.Valid {
			pn.room_path_nodes = new(int)
			*pn.room_path_nodes = int(value.Int64)
		}
	}
	return nil
}

// QueryDoor queries the door edge of the PathNode.
func (pn *PathNode) QueryDoor() *DoorQuery {
	return (&PathNodeClient{pn.config}).QueryDoor(pn)
}

// QueryRoom queries the room edge of the PathNode.
func (pn *PathNode) QueryRoom() *RoomQuery {
	return (&PathNodeClient{pn.config}).QueryRoom(pn)
}

// QueryLinkedFrom queries the linkedFrom edge of the PathNode.
func (pn *PathNode) QueryLinkedFrom() *PathNodeQuery {
	return (&PathNodeClient{pn.config}).QueryLinkedFrom(pn)
}

// QueryLinkedTo queries the linkedTo edge of the PathNode.
func (pn *PathNode) QueryLinkedTo() *PathNodeQuery {
	return (&PathNodeClient{pn.config}).QueryLinkedTo(pn)
}

// Update returns a builder for updating this PathNode.
// Note that, you need to call PathNode.Unwrap() before calling this method, if this PathNode
// was returned from a transaction, and the transaction was committed or rolled back.
func (pn *PathNode) Update() *PathNodeUpdateOne {
	return (&PathNodeClient{pn.config}).UpdateOne(pn)
}

// Unwrap unwraps the entity that was returned from a transaction after it was closed,
// so that all next queries will be executed through the driver which created the transaction.
func (pn *PathNode) Unwrap() *PathNode {
	tx, ok := pn.config.driver.(*txDriver)
	if !ok {
		panic("ent: PathNode is not a transactional entity")
	}
	pn.config.driver = tx.drv
	return pn
}

// String implements the fmt.Stringer.
func (pn *PathNode) String() string {
	var builder strings.Builder
	builder.WriteString("PathNode(")
	builder.WriteString(fmt.Sprintf("id=%v", pn.ID))
	builder.WriteString(", Id=")
	builder.WriteString(fmt.Sprintf("%v", pn.ID))
	builder.WriteString(", X_Coordinate=")
	builder.WriteString(fmt.Sprintf("%v", pn.XCoordinate))
	builder.WriteString(", Y_Coordinate=")
	builder.WriteString(fmt.Sprintf("%v", pn.YCoordinate))
	builder.WriteString(", Floor=")
	builder.WriteString(fmt.Sprintf("%v", pn.Floor))
	builder.WriteByte(')')
	return builder.String()
}

// PathNodes is a parsable slice of PathNode.
type PathNodes []*PathNode

func (pn PathNodes) config(cfg config) {
	for _i := range pn {
		pn[_i].config = cfg
	}
}
