// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"errors"
	"fmt"
	"math"
	"studi-guide/ent/door"
	"studi-guide/ent/pathnode"
	"studi-guide/ent/predicate"
	"studi-guide/ent/room"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// PathNodeQuery is the builder for querying PathNode entities.
type PathNodeQuery struct {
	config
	limit      *int
	offset     *int
	order      []Order
	unique     []string
	predicates []predicate.PathNode
	// eager-loading edges.
	withDoor       *DoorQuery
	withRoom       *RoomQuery
	withLinkedFrom *PathNodeQuery
	withLinkedTo   *PathNodeQuery
	withFKs        bool
	// intermediate query.
	sql *sql.Selector
}

// Where adds a new predicate for the builder.
func (pnq *PathNodeQuery) Where(ps ...predicate.PathNode) *PathNodeQuery {
	pnq.predicates = append(pnq.predicates, ps...)
	return pnq
}

// Limit adds a limit step to the query.
func (pnq *PathNodeQuery) Limit(limit int) *PathNodeQuery {
	pnq.limit = &limit
	return pnq
}

// Offset adds an offset step to the query.
func (pnq *PathNodeQuery) Offset(offset int) *PathNodeQuery {
	pnq.offset = &offset
	return pnq
}

// Order adds an order step to the query.
func (pnq *PathNodeQuery) Order(o ...Order) *PathNodeQuery {
	pnq.order = append(pnq.order, o...)
	return pnq
}

// QueryDoor chains the current query on the door edge.
func (pnq *PathNodeQuery) QueryDoor() *DoorQuery {
	query := &DoorQuery{config: pnq.config}
	step := sqlgraph.NewStep(
		sqlgraph.From(pathnode.Table, pathnode.FieldID, pnq.sqlQuery()),
		sqlgraph.To(door.Table, door.FieldID),
		sqlgraph.Edge(sqlgraph.O2O, true, pathnode.DoorTable, pathnode.DoorColumn),
	)
	query.sql = sqlgraph.SetNeighbors(pnq.driver.Dialect(), step)
	return query
}

// QueryRoom chains the current query on the room edge.
func (pnq *PathNodeQuery) QueryRoom() *RoomQuery {
	query := &RoomQuery{config: pnq.config}
	step := sqlgraph.NewStep(
		sqlgraph.From(pathnode.Table, pathnode.FieldID, pnq.sqlQuery()),
		sqlgraph.To(room.Table, room.FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, pathnode.RoomTable, pathnode.RoomColumn),
	)
	query.sql = sqlgraph.SetNeighbors(pnq.driver.Dialect(), step)
	return query
}

// QueryLinkedFrom chains the current query on the linkedFrom edge.
func (pnq *PathNodeQuery) QueryLinkedFrom() *PathNodeQuery {
	query := &PathNodeQuery{config: pnq.config}
	step := sqlgraph.NewStep(
		sqlgraph.From(pathnode.Table, pathnode.FieldID, pnq.sqlQuery()),
		sqlgraph.To(pathnode.Table, pathnode.FieldID),
		sqlgraph.Edge(sqlgraph.M2M, true, pathnode.LinkedFromTable, pathnode.LinkedFromPrimaryKey...),
	)
	query.sql = sqlgraph.SetNeighbors(pnq.driver.Dialect(), step)
	return query
}

// QueryLinkedTo chains the current query on the linkedTo edge.
func (pnq *PathNodeQuery) QueryLinkedTo() *PathNodeQuery {
	query := &PathNodeQuery{config: pnq.config}
	step := sqlgraph.NewStep(
		sqlgraph.From(pathnode.Table, pathnode.FieldID, pnq.sqlQuery()),
		sqlgraph.To(pathnode.Table, pathnode.FieldID),
		sqlgraph.Edge(sqlgraph.M2M, false, pathnode.LinkedToTable, pathnode.LinkedToPrimaryKey...),
	)
	query.sql = sqlgraph.SetNeighbors(pnq.driver.Dialect(), step)
	return query
}

// First returns the first PathNode entity in the query. Returns *NotFoundError when no pathnode was found.
func (pnq *PathNodeQuery) First(ctx context.Context) (*PathNode, error) {
	pns, err := pnq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(pns) == 0 {
		return nil, &NotFoundError{pathnode.Label}
	}
	return pns[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (pnq *PathNodeQuery) FirstX(ctx context.Context) *PathNode {
	pn, err := pnq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return pn
}

// FirstID returns the first PathNode id in the query. Returns *NotFoundError when no id was found.
func (pnq *PathNodeQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = pnq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{pathnode.Label}
		return
	}
	return ids[0], nil
}

// FirstXID is like FirstID, but panics if an error occurs.
func (pnq *PathNodeQuery) FirstXID(ctx context.Context) int {
	id, err := pnq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns the only PathNode entity in the query, returns an error if not exactly one entity was returned.
func (pnq *PathNodeQuery) Only(ctx context.Context) (*PathNode, error) {
	pns, err := pnq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(pns) {
	case 1:
		return pns[0], nil
	case 0:
		return nil, &NotFoundError{pathnode.Label}
	default:
		return nil, &NotSingularError{pathnode.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (pnq *PathNodeQuery) OnlyX(ctx context.Context) *PathNode {
	pn, err := pnq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return pn
}

// OnlyID returns the only PathNode id in the query, returns an error if not exactly one id was returned.
func (pnq *PathNodeQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = pnq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{pathnode.Label}
	default:
		err = &NotSingularError{pathnode.Label}
	}
	return
}

// OnlyXID is like OnlyID, but panics if an error occurs.
func (pnq *PathNodeQuery) OnlyXID(ctx context.Context) int {
	id, err := pnq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of PathNodes.
func (pnq *PathNodeQuery) All(ctx context.Context) ([]*PathNode, error) {
	return pnq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (pnq *PathNodeQuery) AllX(ctx context.Context) []*PathNode {
	pns, err := pnq.All(ctx)
	if err != nil {
		panic(err)
	}
	return pns
}

// IDs executes the query and returns a list of PathNode ids.
func (pnq *PathNodeQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := pnq.Select(pathnode.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (pnq *PathNodeQuery) IDsX(ctx context.Context) []int {
	ids, err := pnq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (pnq *PathNodeQuery) Count(ctx context.Context) (int, error) {
	return pnq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (pnq *PathNodeQuery) CountX(ctx context.Context) int {
	count, err := pnq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (pnq *PathNodeQuery) Exist(ctx context.Context) (bool, error) {
	return pnq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (pnq *PathNodeQuery) ExistX(ctx context.Context) bool {
	exist, err := pnq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the query builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (pnq *PathNodeQuery) Clone() *PathNodeQuery {
	return &PathNodeQuery{
		config:     pnq.config,
		limit:      pnq.limit,
		offset:     pnq.offset,
		order:      append([]Order{}, pnq.order...),
		unique:     append([]string{}, pnq.unique...),
		predicates: append([]predicate.PathNode{}, pnq.predicates...),
		// clone intermediate query.
		sql: pnq.sql.Clone(),
	}
}

//  WithDoor tells the query-builder to eager-loads the nodes that are connected to
// the "door" edge. The optional arguments used to configure the query builder of the edge.
func (pnq *PathNodeQuery) WithDoor(opts ...func(*DoorQuery)) *PathNodeQuery {
	query := &DoorQuery{config: pnq.config}
	for _, opt := range opts {
		opt(query)
	}
	pnq.withDoor = query
	return pnq
}

//  WithRoom tells the query-builder to eager-loads the nodes that are connected to
// the "room" edge. The optional arguments used to configure the query builder of the edge.
func (pnq *PathNodeQuery) WithRoom(opts ...func(*RoomQuery)) *PathNodeQuery {
	query := &RoomQuery{config: pnq.config}
	for _, opt := range opts {
		opt(query)
	}
	pnq.withRoom = query
	return pnq
}

//  WithLinkedFrom tells the query-builder to eager-loads the nodes that are connected to
// the "linkedFrom" edge. The optional arguments used to configure the query builder of the edge.
func (pnq *PathNodeQuery) WithLinkedFrom(opts ...func(*PathNodeQuery)) *PathNodeQuery {
	query := &PathNodeQuery{config: pnq.config}
	for _, opt := range opts {
		opt(query)
	}
	pnq.withLinkedFrom = query
	return pnq
}

//  WithLinkedTo tells the query-builder to eager-loads the nodes that are connected to
// the "linkedTo" edge. The optional arguments used to configure the query builder of the edge.
func (pnq *PathNodeQuery) WithLinkedTo(opts ...func(*PathNodeQuery)) *PathNodeQuery {
	query := &PathNodeQuery{config: pnq.config}
	for _, opt := range opts {
		opt(query)
	}
	pnq.withLinkedTo = query
	return pnq
}

// GroupBy used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		XCoordinate int `json:"X_Coordinate,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.PathNode.Query().
//		GroupBy(pathnode.FieldXCoordinate).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (pnq *PathNodeQuery) GroupBy(field string, fields ...string) *PathNodeGroupBy {
	group := &PathNodeGroupBy{config: pnq.config}
	group.fields = append([]string{field}, fields...)
	group.sql = pnq.sqlQuery()
	return group
}

// Select one or more fields from the given query.
//
// Example:
//
//	var v []struct {
//		XCoordinate int `json:"X_Coordinate,omitempty"`
//	}
//
//	client.PathNode.Query().
//		Select(pathnode.FieldXCoordinate).
//		Scan(ctx, &v)
//
func (pnq *PathNodeQuery) Select(field string, fields ...string) *PathNodeSelect {
	selector := &PathNodeSelect{config: pnq.config}
	selector.fields = append([]string{field}, fields...)
	selector.sql = pnq.sqlQuery()
	return selector
}

func (pnq *PathNodeQuery) sqlAll(ctx context.Context) ([]*PathNode, error) {
	var (
		nodes       = []*PathNode{}
		withFKs     = pnq.withFKs
		_spec       = pnq.querySpec()
		loadedTypes = [4]bool{
			pnq.withDoor != nil,
			pnq.withRoom != nil,
			pnq.withLinkedFrom != nil,
			pnq.withLinkedTo != nil,
		}
	)
	if pnq.withDoor != nil || pnq.withRoom != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, pathnode.ForeignKeys...)
	}
	_spec.ScanValues = func() []interface{} {
		node := &PathNode{config: pnq.config}
		nodes = append(nodes, node)
		values := node.scanValues()
		if withFKs {
			values = append(values, node.fkValues()...)
		}
		return values
	}
	_spec.Assign = func(values ...interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(values...)
	}
	if err := sqlgraph.QueryNodes(ctx, pnq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}

	if query := pnq.withDoor; query != nil {
		ids := make([]int, 0, len(nodes))
		nodeids := make(map[int][]*PathNode)
		for i := range nodes {
			if fk := nodes[i].door_path_nodes; fk != nil {
				ids = append(ids, *fk)
				nodeids[*fk] = append(nodeids[*fk], nodes[i])
			}
		}
		query.Where(door.IDIn(ids...))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			nodes, ok := nodeids[n.ID]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "door_path_nodes" returned %v`, n.ID)
			}
			for i := range nodes {
				nodes[i].Edges.Door = n
			}
		}
	}

	if query := pnq.withRoom; query != nil {
		ids := make([]int, 0, len(nodes))
		nodeids := make(map[int][]*PathNode)
		for i := range nodes {
			if fk := nodes[i].room_path_nodes; fk != nil {
				ids = append(ids, *fk)
				nodeids[*fk] = append(nodeids[*fk], nodes[i])
			}
		}
		query.Where(room.IDIn(ids...))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			nodes, ok := nodeids[n.ID]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "room_path_nodes" returned %v`, n.ID)
			}
			for i := range nodes {
				nodes[i].Edges.Room = n
			}
		}
	}

	if query := pnq.withLinkedFrom; query != nil {
		fks := make([]driver.Value, 0, len(nodes))
		ids := make(map[int]*PathNode, len(nodes))
		for _, node := range nodes {
			ids[node.ID] = node
			fks = append(fks, node.ID)
		}
		var (
			edgeids []int
			edges   = make(map[int][]*PathNode)
		)
		_spec := &sqlgraph.EdgeQuerySpec{
			Edge: &sqlgraph.EdgeSpec{
				Inverse: true,
				Table:   pathnode.LinkedFromTable,
				Columns: pathnode.LinkedFromPrimaryKey,
			},
			Predicate: func(s *sql.Selector) {
				s.Where(sql.InValues(pathnode.LinkedFromPrimaryKey[1], fks...))
			},

			ScanValues: func() [2]interface{} {
				return [2]interface{}{&sql.NullInt64{}, &sql.NullInt64{}}
			},
			Assign: func(out, in interface{}) error {
				eout, ok := out.(*sql.NullInt64)
				if !ok || eout == nil {
					return fmt.Errorf("unexpected id value for edge-out")
				}
				ein, ok := in.(*sql.NullInt64)
				if !ok || ein == nil {
					return fmt.Errorf("unexpected id value for edge-in")
				}
				outValue := int(eout.Int64)
				inValue := int(ein.Int64)
				node, ok := ids[outValue]
				if !ok {
					return fmt.Errorf("unexpected node id in edges: %v", outValue)
				}
				edgeids = append(edgeids, inValue)
				edges[inValue] = append(edges[inValue], node)
				return nil
			},
		}
		if err := sqlgraph.QueryEdges(ctx, pnq.driver, _spec); err != nil {
			return nil, fmt.Errorf(`query edges "linkedFrom": %v`, err)
		}
		query.Where(pathnode.IDIn(edgeids...))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			nodes, ok := edges[n.ID]
			if !ok {
				return nil, fmt.Errorf(`unexpected "linkedFrom" node returned %v`, n.ID)
			}
			for i := range nodes {
				nodes[i].Edges.LinkedFrom = append(nodes[i].Edges.LinkedFrom, n)
			}
		}
	}

	if query := pnq.withLinkedTo; query != nil {
		fks := make([]driver.Value, 0, len(nodes))
		ids := make(map[int]*PathNode, len(nodes))
		for _, node := range nodes {
			ids[node.ID] = node
			fks = append(fks, node.ID)
		}
		var (
			edgeids []int
			edges   = make(map[int][]*PathNode)
		)
		_spec := &sqlgraph.EdgeQuerySpec{
			Edge: &sqlgraph.EdgeSpec{
				Inverse: false,
				Table:   pathnode.LinkedToTable,
				Columns: pathnode.LinkedToPrimaryKey,
			},
			Predicate: func(s *sql.Selector) {
				s.Where(sql.InValues(pathnode.LinkedToPrimaryKey[0], fks...))
			},

			ScanValues: func() [2]interface{} {
				return [2]interface{}{&sql.NullInt64{}, &sql.NullInt64{}}
			},
			Assign: func(out, in interface{}) error {
				eout, ok := out.(*sql.NullInt64)
				if !ok || eout == nil {
					return fmt.Errorf("unexpected id value for edge-out")
				}
				ein, ok := in.(*sql.NullInt64)
				if !ok || ein == nil {
					return fmt.Errorf("unexpected id value for edge-in")
				}
				outValue := int(eout.Int64)
				inValue := int(ein.Int64)
				node, ok := ids[outValue]
				if !ok {
					return fmt.Errorf("unexpected node id in edges: %v", outValue)
				}
				edgeids = append(edgeids, inValue)
				edges[inValue] = append(edges[inValue], node)
				return nil
			},
		}
		if err := sqlgraph.QueryEdges(ctx, pnq.driver, _spec); err != nil {
			return nil, fmt.Errorf(`query edges "linkedTo": %v`, err)
		}
		query.Where(pathnode.IDIn(edgeids...))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			nodes, ok := edges[n.ID]
			if !ok {
				return nil, fmt.Errorf(`unexpected "linkedTo" node returned %v`, n.ID)
			}
			for i := range nodes {
				nodes[i].Edges.LinkedTo = append(nodes[i].Edges.LinkedTo, n)
			}
		}
	}

	return nodes, nil
}

func (pnq *PathNodeQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := pnq.querySpec()
	return sqlgraph.CountNodes(ctx, pnq.driver, _spec)
}

func (pnq *PathNodeQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := pnq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %v", err)
	}
	return n > 0, nil
}

func (pnq *PathNodeQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   pathnode.Table,
			Columns: pathnode.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: pathnode.FieldID,
			},
		},
		From:   pnq.sql,
		Unique: true,
	}
	if ps := pnq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := pnq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := pnq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := pnq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (pnq *PathNodeQuery) sqlQuery() *sql.Selector {
	builder := sql.Dialect(pnq.driver.Dialect())
	t1 := builder.Table(pathnode.Table)
	selector := builder.Select(t1.Columns(pathnode.Columns...)...).From(t1)
	if pnq.sql != nil {
		selector = pnq.sql
		selector.Select(selector.Columns(pathnode.Columns...)...)
	}
	for _, p := range pnq.predicates {
		p(selector)
	}
	for _, p := range pnq.order {
		p(selector)
	}
	if offset := pnq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := pnq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// PathNodeGroupBy is the builder for group-by PathNode entities.
type PathNodeGroupBy struct {
	config
	fields []string
	fns    []Aggregate
	// intermediate query.
	sql *sql.Selector
}

// Aggregate adds the given aggregation functions to the group-by query.
func (pngb *PathNodeGroupBy) Aggregate(fns ...Aggregate) *PathNodeGroupBy {
	pngb.fns = append(pngb.fns, fns...)
	return pngb
}

// Scan applies the group-by query and scan the result into the given value.
func (pngb *PathNodeGroupBy) Scan(ctx context.Context, v interface{}) error {
	return pngb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (pngb *PathNodeGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := pngb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by. It is only allowed when querying group-by with one field.
func (pngb *PathNodeGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(pngb.fields) > 1 {
		return nil, errors.New("ent: PathNodeGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := pngb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (pngb *PathNodeGroupBy) StringsX(ctx context.Context) []string {
	v, err := pngb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by. It is only allowed when querying group-by with one field.
func (pngb *PathNodeGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(pngb.fields) > 1 {
		return nil, errors.New("ent: PathNodeGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := pngb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (pngb *PathNodeGroupBy) IntsX(ctx context.Context) []int {
	v, err := pngb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by. It is only allowed when querying group-by with one field.
func (pngb *PathNodeGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(pngb.fields) > 1 {
		return nil, errors.New("ent: PathNodeGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := pngb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (pngb *PathNodeGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := pngb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by. It is only allowed when querying group-by with one field.
func (pngb *PathNodeGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(pngb.fields) > 1 {
		return nil, errors.New("ent: PathNodeGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := pngb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (pngb *PathNodeGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := pngb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (pngb *PathNodeGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := pngb.sqlQuery().Query()
	if err := pngb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (pngb *PathNodeGroupBy) sqlQuery() *sql.Selector {
	selector := pngb.sql
	columns := make([]string, 0, len(pngb.fields)+len(pngb.fns))
	columns = append(columns, pngb.fields...)
	for _, fn := range pngb.fns {
		columns = append(columns, fn(selector))
	}
	return selector.Select(columns...).GroupBy(pngb.fields...)
}

// PathNodeSelect is the builder for select fields of PathNode entities.
type PathNodeSelect struct {
	config
	fields []string
	// intermediate queries.
	sql *sql.Selector
}

// Scan applies the selector query and scan the result into the given value.
func (pns *PathNodeSelect) Scan(ctx context.Context, v interface{}) error {
	return pns.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (pns *PathNodeSelect) ScanX(ctx context.Context, v interface{}) {
	if err := pns.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from selector. It is only allowed when selecting one field.
func (pns *PathNodeSelect) Strings(ctx context.Context) ([]string, error) {
	if len(pns.fields) > 1 {
		return nil, errors.New("ent: PathNodeSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := pns.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (pns *PathNodeSelect) StringsX(ctx context.Context) []string {
	v, err := pns.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from selector. It is only allowed when selecting one field.
func (pns *PathNodeSelect) Ints(ctx context.Context) ([]int, error) {
	if len(pns.fields) > 1 {
		return nil, errors.New("ent: PathNodeSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := pns.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (pns *PathNodeSelect) IntsX(ctx context.Context) []int {
	v, err := pns.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from selector. It is only allowed when selecting one field.
func (pns *PathNodeSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(pns.fields) > 1 {
		return nil, errors.New("ent: PathNodeSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := pns.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (pns *PathNodeSelect) Float64sX(ctx context.Context) []float64 {
	v, err := pns.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from selector. It is only allowed when selecting one field.
func (pns *PathNodeSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(pns.fields) > 1 {
		return nil, errors.New("ent: PathNodeSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := pns.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (pns *PathNodeSelect) BoolsX(ctx context.Context) []bool {
	v, err := pns.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (pns *PathNodeSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := pns.sqlQuery().Query()
	if err := pns.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (pns *PathNodeSelect) sqlQuery() sql.Querier {
	selector := pns.sql
	selector.Select(selector.Columns(pns.fields...)...)
	return selector
}
