// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"studi-guide/ent/door"
	"studi-guide/ent/pathnode"
	"studi-guide/ent/room"

	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// PathNodeCreate is the builder for creating a PathNode entity.
type PathNodeCreate struct {
	config
	Id           *int
	X_Coordinate *int
	Y_Coordinate *int
	Floor        *int
	door         map[int]struct{}
	room         map[int]struct{}
	linkedFrom   map[int]struct{}
	linkedTo     map[int]struct{}
}

// SetID sets the Id field.
func (pnc *PathNodeCreate) SetID(i int) *PathNodeCreate {
	pnc.Id = &i
	return pnc
}

// SetXCoordinate sets the X_Coordinate field.
func (pnc *PathNodeCreate) SetXCoordinate(i int) *PathNodeCreate {
	pnc.X_Coordinate = &i
	return pnc
}

// SetNillableXCoordinate sets the X_Coordinate field if the given value is not nil.
func (pnc *PathNodeCreate) SetNillableXCoordinate(i *int) *PathNodeCreate {
	if i != nil {
		pnc.SetXCoordinate(*i)
	}
	return pnc
}

// SetYCoordinate sets the Y_Coordinate field.
func (pnc *PathNodeCreate) SetYCoordinate(i int) *PathNodeCreate {
	pnc.Y_Coordinate = &i
	return pnc
}

// SetNillableYCoordinate sets the Y_Coordinate field if the given value is not nil.
func (pnc *PathNodeCreate) SetNillableYCoordinate(i *int) *PathNodeCreate {
	if i != nil {
		pnc.SetYCoordinate(*i)
	}
	return pnc
}

// SetFloor sets the Floor field.
func (pnc *PathNodeCreate) SetFloor(i int) *PathNodeCreate {
	pnc.Floor = &i
	return pnc
}

// SetNillableFloor sets the Floor field if the given value is not nil.
func (pnc *PathNodeCreate) SetNillableFloor(i *int) *PathNodeCreate {
	if i != nil {
		pnc.SetFloor(*i)
	}
	return pnc
}

// SetDoorID sets the door edge to Door by id.
func (pnc *PathNodeCreate) SetDoorID(id int) *PathNodeCreate {
	if pnc.door == nil {
		pnc.door = make(map[int]struct{})
	}
	pnc.door[id] = struct{}{}
	return pnc
}

// SetNillableDoorID sets the door edge to Door by id if the given value is not nil.
func (pnc *PathNodeCreate) SetNillableDoorID(id *int) *PathNodeCreate {
	if id != nil {
		pnc = pnc.SetDoorID(*id)
	}
	return pnc
}

// SetDoor sets the door edge to Door.
func (pnc *PathNodeCreate) SetDoor(d *Door) *PathNodeCreate {
	return pnc.SetDoorID(d.ID)
}

// SetRoomID sets the room edge to Room by id.
func (pnc *PathNodeCreate) SetRoomID(id int) *PathNodeCreate {
	if pnc.room == nil {
		pnc.room = make(map[int]struct{})
	}
	pnc.room[id] = struct{}{}
	return pnc
}

// SetNillableRoomID sets the room edge to Room by id if the given value is not nil.
func (pnc *PathNodeCreate) SetNillableRoomID(id *int) *PathNodeCreate {
	if id != nil {
		pnc = pnc.SetRoomID(*id)
	}
	return pnc
}

// SetRoom sets the room edge to Room.
func (pnc *PathNodeCreate) SetRoom(r *Room) *PathNodeCreate {
	return pnc.SetRoomID(r.ID)
}

// AddLinkedFromIDs adds the linkedFrom edge to PathNode by ids.
func (pnc *PathNodeCreate) AddLinkedFromIDs(ids ...int) *PathNodeCreate {
	if pnc.linkedFrom == nil {
		pnc.linkedFrom = make(map[int]struct{})
	}
	for i := range ids {
		pnc.linkedFrom[ids[i]] = struct{}{}
	}
	return pnc
}

// AddLinkedFrom adds the linkedFrom edges to PathNode.
func (pnc *PathNodeCreate) AddLinkedFrom(p ...*PathNode) *PathNodeCreate {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return pnc.AddLinkedFromIDs(ids...)
}

// AddLinkedToIDs adds the linkedTo edge to PathNode by ids.
func (pnc *PathNodeCreate) AddLinkedToIDs(ids ...int) *PathNodeCreate {
	if pnc.linkedTo == nil {
		pnc.linkedTo = make(map[int]struct{})
	}
	for i := range ids {
		pnc.linkedTo[ids[i]] = struct{}{}
	}
	return pnc
}

// AddLinkedTo adds the linkedTo edges to PathNode.
func (pnc *PathNodeCreate) AddLinkedTo(p ...*PathNode) *PathNodeCreate {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return pnc.AddLinkedToIDs(ids...)
}

// Save creates the PathNode in the database.
func (pnc *PathNodeCreate) Save(ctx context.Context) (*PathNode, error) {
	if pnc.Id == nil {
		return nil, errors.New("ent: missing required field \"Id\"")
	}
	if pnc.X_Coordinate == nil {
		v := pathnode.DefaultXCoordinate
		pnc.X_Coordinate = &v
	}
	if pnc.Y_Coordinate == nil {
		v := pathnode.DefaultYCoordinate
		pnc.Y_Coordinate = &v
	}
	if pnc.Floor == nil {
		v := pathnode.DefaultFloor
		pnc.Floor = &v
	}
	if len(pnc.door) > 1 {
		return nil, errors.New("ent: multiple assignments on a unique edge \"door\"")
	}
	if len(pnc.room) > 1 {
		return nil, errors.New("ent: multiple assignments on a unique edge \"room\"")
	}
	return pnc.sqlSave(ctx)
}

// SaveX calls Save and panics if Save returns an error.
func (pnc *PathNodeCreate) SaveX(ctx context.Context) *PathNode {
	v, err := pnc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (pnc *PathNodeCreate) sqlSave(ctx context.Context) (*PathNode, error) {
	var (
		pn    = &PathNode{config: pnc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: pathnode.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: pathnode.FieldID,
			},
		}
	)
	if value := pnc.Id; value != nil {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  *value,
			Column: pathnode.FieldID,
		})
		pn.ID = *value
	}
	if value := pnc.X_Coordinate; value != nil {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  *value,
			Column: pathnode.FieldXCoordinate,
		})
		pn.XCoordinate = *value
	}
	if value := pnc.Y_Coordinate; value != nil {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  *value,
			Column: pathnode.FieldYCoordinate,
		})
		pn.YCoordinate = *value
	}
	if value := pnc.Floor; value != nil {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  *value,
			Column: pathnode.FieldFloor,
		})
		pn.Floor = *value
	}
	if nodes := pnc.door; len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   pathnode.DoorTable,
			Columns: []string{pathnode.DoorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: door.FieldID,
				},
			},
		}
		for k, _ := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := pnc.room; len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pathnode.RoomTable,
			Columns: []string{pathnode.RoomColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: room.FieldID,
				},
			},
		}
		for k, _ := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := pnc.linkedFrom; len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   pathnode.LinkedFromTable,
			Columns: pathnode.LinkedFromPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: pathnode.FieldID,
				},
			},
		}
		for k, _ := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := pnc.linkedTo; len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   pathnode.LinkedToTable,
			Columns: pathnode.LinkedToPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: pathnode.FieldID,
				},
			},
		}
		for k, _ := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if err := sqlgraph.CreateNode(ctx, pnc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	pn.ID = int(id)
	return pn, nil
}
