// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"studi-guide/ent/door"
	"studi-guide/ent/pathnode"
	"studi-guide/ent/predicate"
	"studi-guide/ent/room"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// PathNodeUpdate is the builder for updating PathNode entities.
type PathNodeUpdate struct {
	config
	X_Coordinate      *int
	addX_Coordinate   *int
	Y_Coordinate      *int
	addY_Coordinate   *int
	Floor             *int
	addFloor          *int
	door              map[int]struct{}
	room              map[int]struct{}
	linkedFrom        map[int]struct{}
	linkedTo          map[int]struct{}
	clearedDoor       bool
	clearedRoom       bool
	removedLinkedFrom map[int]struct{}
	removedLinkedTo   map[int]struct{}
	predicates        []predicate.PathNode
}

// Where adds a new predicate for the builder.
func (pnu *PathNodeUpdate) Where(ps ...predicate.PathNode) *PathNodeUpdate {
	pnu.predicates = append(pnu.predicates, ps...)
	return pnu
}

// SetXCoordinate sets the X_Coordinate field.
func (pnu *PathNodeUpdate) SetXCoordinate(i int) *PathNodeUpdate {
	pnu.X_Coordinate = &i
	pnu.addX_Coordinate = nil
	return pnu
}

// SetNillableXCoordinate sets the X_Coordinate field if the given value is not nil.
func (pnu *PathNodeUpdate) SetNillableXCoordinate(i *int) *PathNodeUpdate {
	if i != nil {
		pnu.SetXCoordinate(*i)
	}
	return pnu
}

// AddXCoordinate adds i to X_Coordinate.
func (pnu *PathNodeUpdate) AddXCoordinate(i int) *PathNodeUpdate {
	if pnu.addX_Coordinate == nil {
		pnu.addX_Coordinate = &i
	} else {
		*pnu.addX_Coordinate += i
	}
	return pnu
}

// SetYCoordinate sets the Y_Coordinate field.
func (pnu *PathNodeUpdate) SetYCoordinate(i int) *PathNodeUpdate {
	pnu.Y_Coordinate = &i
	pnu.addY_Coordinate = nil
	return pnu
}

// SetNillableYCoordinate sets the Y_Coordinate field if the given value is not nil.
func (pnu *PathNodeUpdate) SetNillableYCoordinate(i *int) *PathNodeUpdate {
	if i != nil {
		pnu.SetYCoordinate(*i)
	}
	return pnu
}

// AddYCoordinate adds i to Y_Coordinate.
func (pnu *PathNodeUpdate) AddYCoordinate(i int) *PathNodeUpdate {
	if pnu.addY_Coordinate == nil {
		pnu.addY_Coordinate = &i
	} else {
		*pnu.addY_Coordinate += i
	}
	return pnu
}

// SetFloor sets the Floor field.
func (pnu *PathNodeUpdate) SetFloor(i int) *PathNodeUpdate {
	pnu.Floor = &i
	pnu.addFloor = nil
	return pnu
}

// SetNillableFloor sets the Floor field if the given value is not nil.
func (pnu *PathNodeUpdate) SetNillableFloor(i *int) *PathNodeUpdate {
	if i != nil {
		pnu.SetFloor(*i)
	}
	return pnu
}

// AddFloor adds i to Floor.
func (pnu *PathNodeUpdate) AddFloor(i int) *PathNodeUpdate {
	if pnu.addFloor == nil {
		pnu.addFloor = &i
	} else {
		*pnu.addFloor += i
	}
	return pnu
}

// SetDoorID sets the door edge to Door by id.
func (pnu *PathNodeUpdate) SetDoorID(id int) *PathNodeUpdate {
	if pnu.door == nil {
		pnu.door = make(map[int]struct{})
	}
	pnu.door[id] = struct{}{}
	return pnu
}

// SetNillableDoorID sets the door edge to Door by id if the given value is not nil.
func (pnu *PathNodeUpdate) SetNillableDoorID(id *int) *PathNodeUpdate {
	if id != nil {
		pnu = pnu.SetDoorID(*id)
	}
	return pnu
}

// SetDoor sets the door edge to Door.
func (pnu *PathNodeUpdate) SetDoor(d *Door) *PathNodeUpdate {
	return pnu.SetDoorID(d.ID)
}

// SetRoomID sets the room edge to Room by id.
func (pnu *PathNodeUpdate) SetRoomID(id int) *PathNodeUpdate {
	if pnu.room == nil {
		pnu.room = make(map[int]struct{})
	}
	pnu.room[id] = struct{}{}
	return pnu
}

// SetNillableRoomID sets the room edge to Room by id if the given value is not nil.
func (pnu *PathNodeUpdate) SetNillableRoomID(id *int) *PathNodeUpdate {
	if id != nil {
		pnu = pnu.SetRoomID(*id)
	}
	return pnu
}

// SetRoom sets the room edge to Room.
func (pnu *PathNodeUpdate) SetRoom(r *Room) *PathNodeUpdate {
	return pnu.SetRoomID(r.ID)
}

// AddLinkedFromIDs adds the linkedFrom edge to PathNode by ids.
func (pnu *PathNodeUpdate) AddLinkedFromIDs(ids ...int) *PathNodeUpdate {
	if pnu.linkedFrom == nil {
		pnu.linkedFrom = make(map[int]struct{})
	}
	for i := range ids {
		pnu.linkedFrom[ids[i]] = struct{}{}
	}
	return pnu
}

// AddLinkedFrom adds the linkedFrom edges to PathNode.
func (pnu *PathNodeUpdate) AddLinkedFrom(p ...*PathNode) *PathNodeUpdate {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return pnu.AddLinkedFromIDs(ids...)
}

// AddLinkedToIDs adds the linkedTo edge to PathNode by ids.
func (pnu *PathNodeUpdate) AddLinkedToIDs(ids ...int) *PathNodeUpdate {
	if pnu.linkedTo == nil {
		pnu.linkedTo = make(map[int]struct{})
	}
	for i := range ids {
		pnu.linkedTo[ids[i]] = struct{}{}
	}
	return pnu
}

// AddLinkedTo adds the linkedTo edges to PathNode.
func (pnu *PathNodeUpdate) AddLinkedTo(p ...*PathNode) *PathNodeUpdate {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return pnu.AddLinkedToIDs(ids...)
}

// ClearDoor clears the door edge to Door.
func (pnu *PathNodeUpdate) ClearDoor() *PathNodeUpdate {
	pnu.clearedDoor = true
	return pnu
}

// ClearRoom clears the room edge to Room.
func (pnu *PathNodeUpdate) ClearRoom() *PathNodeUpdate {
	pnu.clearedRoom = true
	return pnu
}

// RemoveLinkedFromIDs removes the linkedFrom edge to PathNode by ids.
func (pnu *PathNodeUpdate) RemoveLinkedFromIDs(ids ...int) *PathNodeUpdate {
	if pnu.removedLinkedFrom == nil {
		pnu.removedLinkedFrom = make(map[int]struct{})
	}
	for i := range ids {
		pnu.removedLinkedFrom[ids[i]] = struct{}{}
	}
	return pnu
}

// RemoveLinkedFrom removes linkedFrom edges to PathNode.
func (pnu *PathNodeUpdate) RemoveLinkedFrom(p ...*PathNode) *PathNodeUpdate {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return pnu.RemoveLinkedFromIDs(ids...)
}

// RemoveLinkedToIDs removes the linkedTo edge to PathNode by ids.
func (pnu *PathNodeUpdate) RemoveLinkedToIDs(ids ...int) *PathNodeUpdate {
	if pnu.removedLinkedTo == nil {
		pnu.removedLinkedTo = make(map[int]struct{})
	}
	for i := range ids {
		pnu.removedLinkedTo[ids[i]] = struct{}{}
	}
	return pnu
}

// RemoveLinkedTo removes linkedTo edges to PathNode.
func (pnu *PathNodeUpdate) RemoveLinkedTo(p ...*PathNode) *PathNodeUpdate {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return pnu.RemoveLinkedToIDs(ids...)
}

// Save executes the query and returns the number of rows/vertices matched by this operation.
func (pnu *PathNodeUpdate) Save(ctx context.Context) (int, error) {
	if len(pnu.door) > 1 {
		return 0, errors.New("ent: multiple assignments on a unique edge \"door\"")
	}
	if len(pnu.room) > 1 {
		return 0, errors.New("ent: multiple assignments on a unique edge \"room\"")
	}
	return pnu.sqlSave(ctx)
}

// SaveX is like Save, but panics if an error occurs.
func (pnu *PathNodeUpdate) SaveX(ctx context.Context) int {
	affected, err := pnu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (pnu *PathNodeUpdate) Exec(ctx context.Context) error {
	_, err := pnu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pnu *PathNodeUpdate) ExecX(ctx context.Context) {
	if err := pnu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (pnu *PathNodeUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   pathnode.Table,
			Columns: pathnode.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: pathnode.FieldID,
			},
		},
	}
	if ps := pnu.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value := pnu.X_Coordinate; value != nil {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  *value,
			Column: pathnode.FieldXCoordinate,
		})
	}
	if value := pnu.addX_Coordinate; value != nil {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  *value,
			Column: pathnode.FieldXCoordinate,
		})
	}
	if value := pnu.Y_Coordinate; value != nil {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  *value,
			Column: pathnode.FieldYCoordinate,
		})
	}
	if value := pnu.addY_Coordinate; value != nil {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  *value,
			Column: pathnode.FieldYCoordinate,
		})
	}
	if value := pnu.Floor; value != nil {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  *value,
			Column: pathnode.FieldFloor,
		})
	}
	if value := pnu.addFloor; value != nil {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  *value,
			Column: pathnode.FieldFloor,
		})
	}
	if pnu.clearedDoor {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   pathnode.DoorTable,
			Columns: []string{pathnode.DoorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: door.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pnu.door; len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   pathnode.DoorTable,
			Columns: []string{pathnode.DoorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: door.FieldID,
				},
			},
		}
		for k, _ := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if pnu.clearedRoom {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pathnode.RoomTable,
			Columns: []string{pathnode.RoomColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: room.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pnu.room; len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pathnode.RoomTable,
			Columns: []string{pathnode.RoomColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: room.FieldID,
				},
			},
		}
		for k, _ := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if nodes := pnu.removedLinkedFrom; len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   pathnode.LinkedFromTable,
			Columns: pathnode.LinkedFromPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: pathnode.FieldID,
				},
			},
		}
		for k, _ := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pnu.linkedFrom; len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   pathnode.LinkedFromTable,
			Columns: pathnode.LinkedFromPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: pathnode.FieldID,
				},
			},
		}
		for k, _ := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if nodes := pnu.removedLinkedTo; len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   pathnode.LinkedToTable,
			Columns: pathnode.LinkedToPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: pathnode.FieldID,
				},
			},
		}
		for k, _ := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pnu.linkedTo; len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   pathnode.LinkedToTable,
			Columns: pathnode.LinkedToPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: pathnode.FieldID,
				},
			},
		}
		for k, _ := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, pnu.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// PathNodeUpdateOne is the builder for updating a single PathNode entity.
type PathNodeUpdateOne struct {
	config
	id                int
	X_Coordinate      *int
	addX_Coordinate   *int
	Y_Coordinate      *int
	addY_Coordinate   *int
	Floor             *int
	addFloor          *int
	door              map[int]struct{}
	room              map[int]struct{}
	linkedFrom        map[int]struct{}
	linkedTo          map[int]struct{}
	clearedDoor       bool
	clearedRoom       bool
	removedLinkedFrom map[int]struct{}
	removedLinkedTo   map[int]struct{}
}

// SetXCoordinate sets the X_Coordinate field.
func (pnuo *PathNodeUpdateOne) SetXCoordinate(i int) *PathNodeUpdateOne {
	pnuo.X_Coordinate = &i
	pnuo.addX_Coordinate = nil
	return pnuo
}

// SetNillableXCoordinate sets the X_Coordinate field if the given value is not nil.
func (pnuo *PathNodeUpdateOne) SetNillableXCoordinate(i *int) *PathNodeUpdateOne {
	if i != nil {
		pnuo.SetXCoordinate(*i)
	}
	return pnuo
}

// AddXCoordinate adds i to X_Coordinate.
func (pnuo *PathNodeUpdateOne) AddXCoordinate(i int) *PathNodeUpdateOne {
	if pnuo.addX_Coordinate == nil {
		pnuo.addX_Coordinate = &i
	} else {
		*pnuo.addX_Coordinate += i
	}
	return pnuo
}

// SetYCoordinate sets the Y_Coordinate field.
func (pnuo *PathNodeUpdateOne) SetYCoordinate(i int) *PathNodeUpdateOne {
	pnuo.Y_Coordinate = &i
	pnuo.addY_Coordinate = nil
	return pnuo
}

// SetNillableYCoordinate sets the Y_Coordinate field if the given value is not nil.
func (pnuo *PathNodeUpdateOne) SetNillableYCoordinate(i *int) *PathNodeUpdateOne {
	if i != nil {
		pnuo.SetYCoordinate(*i)
	}
	return pnuo
}

// AddYCoordinate adds i to Y_Coordinate.
func (pnuo *PathNodeUpdateOne) AddYCoordinate(i int) *PathNodeUpdateOne {
	if pnuo.addY_Coordinate == nil {
		pnuo.addY_Coordinate = &i
	} else {
		*pnuo.addY_Coordinate += i
	}
	return pnuo
}

// SetFloor sets the Floor field.
func (pnuo *PathNodeUpdateOne) SetFloor(i int) *PathNodeUpdateOne {
	pnuo.Floor = &i
	pnuo.addFloor = nil
	return pnuo
}

// SetNillableFloor sets the Floor field if the given value is not nil.
func (pnuo *PathNodeUpdateOne) SetNillableFloor(i *int) *PathNodeUpdateOne {
	if i != nil {
		pnuo.SetFloor(*i)
	}
	return pnuo
}

// AddFloor adds i to Floor.
func (pnuo *PathNodeUpdateOne) AddFloor(i int) *PathNodeUpdateOne {
	if pnuo.addFloor == nil {
		pnuo.addFloor = &i
	} else {
		*pnuo.addFloor += i
	}
	return pnuo
}

// SetDoorID sets the door edge to Door by id.
func (pnuo *PathNodeUpdateOne) SetDoorID(id int) *PathNodeUpdateOne {
	if pnuo.door == nil {
		pnuo.door = make(map[int]struct{})
	}
	pnuo.door[id] = struct{}{}
	return pnuo
}

// SetNillableDoorID sets the door edge to Door by id if the given value is not nil.
func (pnuo *PathNodeUpdateOne) SetNillableDoorID(id *int) *PathNodeUpdateOne {
	if id != nil {
		pnuo = pnuo.SetDoorID(*id)
	}
	return pnuo
}

// SetDoor sets the door edge to Door.
func (pnuo *PathNodeUpdateOne) SetDoor(d *Door) *PathNodeUpdateOne {
	return pnuo.SetDoorID(d.ID)
}

// SetRoomID sets the room edge to Room by id.
func (pnuo *PathNodeUpdateOne) SetRoomID(id int) *PathNodeUpdateOne {
	if pnuo.room == nil {
		pnuo.room = make(map[int]struct{})
	}
	pnuo.room[id] = struct{}{}
	return pnuo
}

// SetNillableRoomID sets the room edge to Room by id if the given value is not nil.
func (pnuo *PathNodeUpdateOne) SetNillableRoomID(id *int) *PathNodeUpdateOne {
	if id != nil {
		pnuo = pnuo.SetRoomID(*id)
	}
	return pnuo
}

// SetRoom sets the room edge to Room.
func (pnuo *PathNodeUpdateOne) SetRoom(r *Room) *PathNodeUpdateOne {
	return pnuo.SetRoomID(r.ID)
}

// AddLinkedFromIDs adds the linkedFrom edge to PathNode by ids.
func (pnuo *PathNodeUpdateOne) AddLinkedFromIDs(ids ...int) *PathNodeUpdateOne {
	if pnuo.linkedFrom == nil {
		pnuo.linkedFrom = make(map[int]struct{})
	}
	for i := range ids {
		pnuo.linkedFrom[ids[i]] = struct{}{}
	}
	return pnuo
}

// AddLinkedFrom adds the linkedFrom edges to PathNode.
func (pnuo *PathNodeUpdateOne) AddLinkedFrom(p ...*PathNode) *PathNodeUpdateOne {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return pnuo.AddLinkedFromIDs(ids...)
}

// AddLinkedToIDs adds the linkedTo edge to PathNode by ids.
func (pnuo *PathNodeUpdateOne) AddLinkedToIDs(ids ...int) *PathNodeUpdateOne {
	if pnuo.linkedTo == nil {
		pnuo.linkedTo = make(map[int]struct{})
	}
	for i := range ids {
		pnuo.linkedTo[ids[i]] = struct{}{}
	}
	return pnuo
}

// AddLinkedTo adds the linkedTo edges to PathNode.
func (pnuo *PathNodeUpdateOne) AddLinkedTo(p ...*PathNode) *PathNodeUpdateOne {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return pnuo.AddLinkedToIDs(ids...)
}

// ClearDoor clears the door edge to Door.
func (pnuo *PathNodeUpdateOne) ClearDoor() *PathNodeUpdateOne {
	pnuo.clearedDoor = true
	return pnuo
}

// ClearRoom clears the room edge to Room.
func (pnuo *PathNodeUpdateOne) ClearRoom() *PathNodeUpdateOne {
	pnuo.clearedRoom = true
	return pnuo
}

// RemoveLinkedFromIDs removes the linkedFrom edge to PathNode by ids.
func (pnuo *PathNodeUpdateOne) RemoveLinkedFromIDs(ids ...int) *PathNodeUpdateOne {
	if pnuo.removedLinkedFrom == nil {
		pnuo.removedLinkedFrom = make(map[int]struct{})
	}
	for i := range ids {
		pnuo.removedLinkedFrom[ids[i]] = struct{}{}
	}
	return pnuo
}

// RemoveLinkedFrom removes linkedFrom edges to PathNode.
func (pnuo *PathNodeUpdateOne) RemoveLinkedFrom(p ...*PathNode) *PathNodeUpdateOne {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return pnuo.RemoveLinkedFromIDs(ids...)
}

// RemoveLinkedToIDs removes the linkedTo edge to PathNode by ids.
func (pnuo *PathNodeUpdateOne) RemoveLinkedToIDs(ids ...int) *PathNodeUpdateOne {
	if pnuo.removedLinkedTo == nil {
		pnuo.removedLinkedTo = make(map[int]struct{})
	}
	for i := range ids {
		pnuo.removedLinkedTo[ids[i]] = struct{}{}
	}
	return pnuo
}

// RemoveLinkedTo removes linkedTo edges to PathNode.
func (pnuo *PathNodeUpdateOne) RemoveLinkedTo(p ...*PathNode) *PathNodeUpdateOne {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return pnuo.RemoveLinkedToIDs(ids...)
}

// Save executes the query and returns the updated entity.
func (pnuo *PathNodeUpdateOne) Save(ctx context.Context) (*PathNode, error) {
	if len(pnuo.door) > 1 {
		return nil, errors.New("ent: multiple assignments on a unique edge \"door\"")
	}
	if len(pnuo.room) > 1 {
		return nil, errors.New("ent: multiple assignments on a unique edge \"room\"")
	}
	return pnuo.sqlSave(ctx)
}

// SaveX is like Save, but panics if an error occurs.
func (pnuo *PathNodeUpdateOne) SaveX(ctx context.Context) *PathNode {
	pn, err := pnuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return pn
}

// Exec executes the query on the entity.
func (pnuo *PathNodeUpdateOne) Exec(ctx context.Context) error {
	_, err := pnuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pnuo *PathNodeUpdateOne) ExecX(ctx context.Context) {
	if err := pnuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (pnuo *PathNodeUpdateOne) sqlSave(ctx context.Context) (pn *PathNode, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   pathnode.Table,
			Columns: pathnode.Columns,
			ID: &sqlgraph.FieldSpec{
				Value:  pnuo.id,
				Type:   field.TypeInt,
				Column: pathnode.FieldID,
			},
		},
	}
	if value := pnuo.X_Coordinate; value != nil {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  *value,
			Column: pathnode.FieldXCoordinate,
		})
	}
	if value := pnuo.addX_Coordinate; value != nil {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  *value,
			Column: pathnode.FieldXCoordinate,
		})
	}
	if value := pnuo.Y_Coordinate; value != nil {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  *value,
			Column: pathnode.FieldYCoordinate,
		})
	}
	if value := pnuo.addY_Coordinate; value != nil {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  *value,
			Column: pathnode.FieldYCoordinate,
		})
	}
	if value := pnuo.Floor; value != nil {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  *value,
			Column: pathnode.FieldFloor,
		})
	}
	if value := pnuo.addFloor; value != nil {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  *value,
			Column: pathnode.FieldFloor,
		})
	}
	if pnuo.clearedDoor {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   pathnode.DoorTable,
			Columns: []string{pathnode.DoorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: door.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pnuo.door; len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   pathnode.DoorTable,
			Columns: []string{pathnode.DoorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: door.FieldID,
				},
			},
		}
		for k, _ := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if pnuo.clearedRoom {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pathnode.RoomTable,
			Columns: []string{pathnode.RoomColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: room.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pnuo.room; len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pathnode.RoomTable,
			Columns: []string{pathnode.RoomColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: room.FieldID,
				},
			},
		}
		for k, _ := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if nodes := pnuo.removedLinkedFrom; len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   pathnode.LinkedFromTable,
			Columns: pathnode.LinkedFromPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: pathnode.FieldID,
				},
			},
		}
		for k, _ := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pnuo.linkedFrom; len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   pathnode.LinkedFromTable,
			Columns: pathnode.LinkedFromPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: pathnode.FieldID,
				},
			},
		}
		for k, _ := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if nodes := pnuo.removedLinkedTo; len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   pathnode.LinkedToTable,
			Columns: pathnode.LinkedToPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: pathnode.FieldID,
				},
			},
		}
		for k, _ := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pnuo.linkedTo; len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   pathnode.LinkedToTable,
			Columns: pathnode.LinkedToPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: pathnode.FieldID,
				},
			},
		}
		for k, _ := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	pn = &PathNode{config: pnuo.config}
	_spec.Assign = pn.assignValues
	_spec.ScanValues = pn.scanValues()
	if err = sqlgraph.UpdateNode(ctx, pnuo.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return pn, nil
}
