// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"studi-guide/ent/pathnode"
	"studi-guide/ent/predicate"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// PathNodeDelete is the builder for deleting a PathNode entity.
type PathNodeDelete struct {
	config
	predicates []predicate.PathNode
}

// Where adds a new predicate to the delete builder.
func (pnd *PathNodeDelete) Where(ps ...predicate.PathNode) *PathNodeDelete {
	pnd.predicates = append(pnd.predicates, ps...)
	return pnd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (pnd *PathNodeDelete) Exec(ctx context.Context) (int, error) {
	return pnd.sqlExec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (pnd *PathNodeDelete) ExecX(ctx context.Context) int {
	n, err := pnd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (pnd *PathNodeDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: pathnode.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: pathnode.FieldID,
			},
		},
	}
	if ps := pnd.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, pnd.driver, _spec)
}

// PathNodeDeleteOne is the builder for deleting a single PathNode entity.
type PathNodeDeleteOne struct {
	pnd *PathNodeDelete
}

// Exec executes the deletion query.
func (pndo *PathNodeDeleteOne) Exec(ctx context.Context) error {
	n, err := pndo.pnd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{pathnode.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (pndo *PathNodeDeleteOne) ExecX(ctx context.Context) {
	pndo.pnd.ExecX(ctx)
}
