// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"studi-guide/ent/room"

	"github.com/facebookincubator/ent/dialect/sql"
)

// Room is the model entity for the Room schema.
type Room struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "Name" field.
	Name string `json:"Name,omitempty"`
	// Description holds the value of the "Description" field.
	Description string `json:"Description,omitempty"`
	// Floor holds the value of the "Floor" field.
	Floor int `json:"Floor,omitempty"`
	// ID holds the value of the "Id" field.
	ID int `json:"Id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the RoomQuery when eager-loading is set.
	Edges RoomEdges `json:"edges"`
}

// RoomEdges holds the relations/edges for other nodes in the graph.
type RoomEdges struct {
	// Doors holds the value of the doors edge.
	Doors []*Door
	// Sequences holds the value of the sequences edge.
	Sequences []*Sequence
	// PathNodes holds the value of the pathNodes edge.
	PathNodes []*PathNode
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// DoorsOrErr returns the Doors value or an error if the edge
// was not loaded in eager-loading.
func (e RoomEdges) DoorsOrErr() ([]*Door, error) {
	if e.loadedTypes[0] {
		return e.Doors, nil
	}
	return nil, &NotLoadedError{edge: "doors"}
}

// SequencesOrErr returns the Sequences value or an error if the edge
// was not loaded in eager-loading.
func (e RoomEdges) SequencesOrErr() ([]*Sequence, error) {
	if e.loadedTypes[1] {
		return e.Sequences, nil
	}
	return nil, &NotLoadedError{edge: "sequences"}
}

// PathNodesOrErr returns the PathNodes value or an error if the edge
// was not loaded in eager-loading.
func (e RoomEdges) PathNodesOrErr() ([]*PathNode, error) {
	if e.loadedTypes[2] {
		return e.PathNodes, nil
	}
	return nil, &NotLoadedError{edge: "pathNodes"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Room) scanValues() []interface{} {
	return []interface{}{
		&sql.NullInt64{},  // id
		&sql.NullString{}, // Name
		&sql.NullString{}, // Description
		&sql.NullInt64{},  // Floor
		&sql.NullInt64{},  // Id
	}
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Room fields.
func (r *Room) assignValues(values ...interface{}) error {
	if m, n := len(values), len(room.Columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	value, ok := values[0].(*sql.NullInt64)
	if !ok {
		return fmt.Errorf("unexpected type %T for field id", value)
	}
	r.ID = int(value.Int64)
	values = values[1:]
	if value, ok := values[0].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field Name", values[0])
	} else if value.Valid {
		r.Name = value.String
	}
	if value, ok := values[1].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field Description", values[1])
	} else if value.Valid {
		r.Description = value.String
	}
	if value, ok := values[2].(*sql.NullInt64); !ok {
		return fmt.Errorf("unexpected type %T for field Floor", values[2])
	} else if value.Valid {
		r.Floor = int(value.Int64)
	}
	if value, ok := values[3].(*sql.NullInt64); !ok {
		return fmt.Errorf("unexpected type %T for field Id", values[3])
	} else if value.Valid {
		r.ID = int(value.Int64)
	}
	return nil
}

// QueryDoors queries the doors edge of the Room.
func (r *Room) QueryDoors() *DoorQuery {
	return (&RoomClient{r.config}).QueryDoors(r)
}

// QuerySequences queries the sequences edge of the Room.
func (r *Room) QuerySequences() *SequenceQuery {
	return (&RoomClient{r.config}).QuerySequences(r)
}

// QueryPathNodes queries the pathNodes edge of the Room.
func (r *Room) QueryPathNodes() *PathNodeQuery {
	return (&RoomClient{r.config}).QueryPathNodes(r)
}

// Update returns a builder for updating this Room.
// Note that, you need to call Room.Unwrap() before calling this method, if this Room
// was returned from a transaction, and the transaction was committed or rolled back.
func (r *Room) Update() *RoomUpdateOne {
	return (&RoomClient{r.config}).UpdateOne(r)
}

// Unwrap unwraps the entity that was returned from a transaction after it was closed,
// so that all next queries will be executed through the driver which created the transaction.
func (r *Room) Unwrap() *Room {
	tx, ok := r.config.driver.(*txDriver)
	if !ok {
		panic("ent: Room is not a transactional entity")
	}
	r.config.driver = tx.drv
	return r
}

// String implements the fmt.Stringer.
func (r *Room) String() string {
	var builder strings.Builder
	builder.WriteString("Room(")
	builder.WriteString(fmt.Sprintf("id=%v", r.ID))
	builder.WriteString(", Name=")
	builder.WriteString(r.Name)
	builder.WriteString(", Description=")
	builder.WriteString(r.Description)
	builder.WriteString(", Floor=")
	builder.WriteString(fmt.Sprintf("%v", r.Floor))
	builder.WriteString(", Id=")
	builder.WriteString(fmt.Sprintf("%v", r.ID))
	builder.WriteByte(')')
	return builder.String()
}

// Rooms is a parsable slice of Room.
type Rooms []*Room

func (r Rooms) config(cfg config) {
	for _i := range r {
		r[_i].config = cfg
	}
}
