// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"studi-guide/ent/predicate"
	"studi-guide/ent/room"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// RoomDelete is the builder for deleting a Room entity.
type RoomDelete struct {
	config
	predicates []predicate.Room
}

// Where adds a new predicate to the delete builder.
func (rd *RoomDelete) Where(ps ...predicate.Room) *RoomDelete {
	rd.predicates = append(rd.predicates, ps...)
	return rd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (rd *RoomDelete) Exec(ctx context.Context) (int, error) {
	return rd.sqlExec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (rd *RoomDelete) ExecX(ctx context.Context) int {
	n, err := rd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (rd *RoomDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: room.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: room.FieldID,
			},
		},
	}
	if ps := rd.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, rd.driver, _spec)
}

// RoomDeleteOne is the builder for deleting a single Room entity.
type RoomDeleteOne struct {
	rd *RoomDelete
}

// Exec executes the deletion query.
func (rdo *RoomDeleteOne) Exec(ctx context.Context) error {
	n, err := rdo.rd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{room.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (rdo *RoomDeleteOne) ExecX(ctx context.Context) {
	rdo.rd.ExecX(ctx)
}
