// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"studi-guide/ent/predicate"
	"studi-guide/ent/sequence"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// SequenceDelete is the builder for deleting a Sequence entity.
type SequenceDelete struct {
	config
	predicates []predicate.Sequence
}

// Where adds a new predicate to the delete builder.
func (sd *SequenceDelete) Where(ps ...predicate.Sequence) *SequenceDelete {
	sd.predicates = append(sd.predicates, ps...)
	return sd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (sd *SequenceDelete) Exec(ctx context.Context) (int, error) {
	return sd.sqlExec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (sd *SequenceDelete) ExecX(ctx context.Context) int {
	n, err := sd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (sd *SequenceDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: sequence.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: sequence.FieldID,
			},
		},
	}
	if ps := sd.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, sd.driver, _spec)
}

// SequenceDeleteOne is the builder for deleting a single Sequence entity.
type SequenceDeleteOne struct {
	sd *SequenceDelete
}

// Exec executes the deletion query.
func (sdo *SequenceDeleteOne) Exec(ctx context.Context) error {
	n, err := sdo.sd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{sequence.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (sdo *SequenceDeleteOne) ExecX(ctx context.Context) {
	sdo.sd.ExecX(ctx)
}
