// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"studi-guide/ent/door"
	"studi-guide/ent/room"
	"studi-guide/ent/sequence"

	"github.com/facebookincubator/ent/dialect/sql"
)

// Sequence is the model entity for the Sequence schema.
type Sequence struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// XStart holds the value of the "X_Start" field.
	XStart int `json:"X_Start,omitempty"`
	// YStart holds the value of the "Y_Start" field.
	YStart int `json:"Y_Start,omitempty"`
	// XEnd holds the value of the "X_End" field.
	XEnd int `json:"X_End,omitempty"`
	// YEnd holds the value of the "Y_End" field.
	YEnd int `json:"Y_End,omitempty"`
	// ID holds the value of the "Id" field.
	ID int `json:"Id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SequenceQuery when eager-loading is set.
	Edges          SequenceEdges `json:"edges"`
	door_sequence  *int
	room_sequences *int
}

// SequenceEdges holds the relations/edges for other nodes in the graph.
type SequenceEdges struct {
	// Door holds the value of the door edge.
	Door *Door
	// Room holds the value of the room edge.
	Room *Room
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// DoorOrErr returns the Door value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SequenceEdges) DoorOrErr() (*Door, error) {
	if e.loadedTypes[0] {
		if e.Door == nil {
			// The edge door was loaded in eager-loading,
			// but was not found.
			return nil, &NotFoundError{label: door.Label}
		}
		return e.Door, nil
	}
	return nil, &NotLoadedError{edge: "door"}
}

// RoomOrErr returns the Room value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SequenceEdges) RoomOrErr() (*Room, error) {
	if e.loadedTypes[1] {
		if e.Room == nil {
			// The edge room was loaded in eager-loading,
			// but was not found.
			return nil, &NotFoundError{label: room.Label}
		}
		return e.Room, nil
	}
	return nil, &NotLoadedError{edge: "room"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Sequence) scanValues() []interface{} {
	return []interface{}{
		&sql.NullInt64{}, // id
		&sql.NullInt64{}, // X_Start
		&sql.NullInt64{}, // Y_Start
		&sql.NullInt64{}, // X_End
		&sql.NullInt64{}, // Y_End
		&sql.NullInt64{}, // Id
	}
}

// fkValues returns the types for scanning foreign-keys values from sql.Rows.
func (*Sequence) fkValues() []interface{} {
	return []interface{}{
		&sql.NullInt64{}, // door_sequence
		&sql.NullInt64{}, // room_sequences
	}
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Sequence fields.
func (s *Sequence) assignValues(values ...interface{}) error {
	if m, n := len(values), len(sequence.Columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	value, ok := values[0].(*sql.NullInt64)
	if !ok {
		return fmt.Errorf("unexpected type %T for field id", value)
	}
	s.ID = int(value.Int64)
	values = values[1:]
	if value, ok := values[0].(*sql.NullInt64); !ok {
		return fmt.Errorf("unexpected type %T for field X_Start", values[0])
	} else if value.Valid {
		s.XStart = int(value.Int64)
	}
	if value, ok := values[1].(*sql.NullInt64); !ok {
		return fmt.Errorf("unexpected type %T for field Y_Start", values[1])
	} else if value.Valid {
		s.YStart = int(value.Int64)
	}
	if value, ok := values[2].(*sql.NullInt64); !ok {
		return fmt.Errorf("unexpected type %T for field X_End", values[2])
	} else if value.Valid {
		s.XEnd = int(value.Int64)
	}
	if value, ok := values[3].(*sql.NullInt64); !ok {
		return fmt.Errorf("unexpected type %T for field Y_End", values[3])
	} else if value.Valid {
		s.YEnd = int(value.Int64)
	}
	if value, ok := values[4].(*sql.NullInt64); !ok {
		return fmt.Errorf("unexpected type %T for field Id", values[4])
	} else if value.Valid {
		s.ID = int(value.Int64)
	}
	values = values[5:]
	if len(values) == len(sequence.ForeignKeys) {
		if value, ok := values[0].(*sql.NullInt64); !ok {
			return fmt.Errorf("unexpected type %T for edge-field door_sequence", value)
		} else if value.Valid {
			s.door_sequence = new(int)
			*s.door_sequence = int(value.Int64)
		}
		if value, ok := values[1].(*sql.NullInt64); !ok {
			return fmt.Errorf("unexpected type %T for edge-field room_sequences", value)
		} else if value.Valid {
			s.room_sequences = new(int)
			*s.room_sequences = int(value.Int64)
		}
	}
	return nil
}

// QueryDoor queries the door edge of the Sequence.
func (s *Sequence) QueryDoor() *DoorQuery {
	return (&SequenceClient{s.config}).QueryDoor(s)
}

// QueryRoom queries the room edge of the Sequence.
func (s *Sequence) QueryRoom() *RoomQuery {
	return (&SequenceClient{s.config}).QueryRoom(s)
}

// Update returns a builder for updating this Sequence.
// Note that, you need to call Sequence.Unwrap() before calling this method, if this Sequence
// was returned from a transaction, and the transaction was committed or rolled back.
func (s *Sequence) Update() *SequenceUpdateOne {
	return (&SequenceClient{s.config}).UpdateOne(s)
}

// Unwrap unwraps the entity that was returned from a transaction after it was closed,
// so that all next queries will be executed through the driver which created the transaction.
func (s *Sequence) Unwrap() *Sequence {
	tx, ok := s.config.driver.(*txDriver)
	if !ok {
		panic("ent: Sequence is not a transactional entity")
	}
	s.config.driver = tx.drv
	return s
}

// String implements the fmt.Stringer.
func (s *Sequence) String() string {
	var builder strings.Builder
	builder.WriteString("Sequence(")
	builder.WriteString(fmt.Sprintf("id=%v", s.ID))
	builder.WriteString(", X_Start=")
	builder.WriteString(fmt.Sprintf("%v", s.XStart))
	builder.WriteString(", Y_Start=")
	builder.WriteString(fmt.Sprintf("%v", s.YStart))
	builder.WriteString(", X_End=")
	builder.WriteString(fmt.Sprintf("%v", s.XEnd))
	builder.WriteString(", Y_End=")
	builder.WriteString(fmt.Sprintf("%v", s.YEnd))
	builder.WriteString(", Id=")
	builder.WriteString(fmt.Sprintf("%v", s.ID))
	builder.WriteByte(')')
	return builder.String()
}

// Sequences is a parsable slice of Sequence.
type Sequences []*Sequence

func (s Sequences) config(cfg config) {
	for _i := range s {
		s[_i].config = cfg
	}
}
