// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"studi-guide/ent/door"
	"studi-guide/ent/predicate"
	"studi-guide/ent/room"
	"studi-guide/ent/sequence"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// SequenceUpdate is the builder for updating Sequence entities.
type SequenceUpdate struct {
	config
	X_Start     *int
	addX_Start  *int
	Y_Start     *int
	addY_Start  *int
	X_End       *int
	addX_End    *int
	Y_End       *int
	addY_End    *int
	door        map[int]struct{}
	room        map[int]struct{}
	clearedDoor bool
	clearedRoom bool
	predicates  []predicate.Sequence
}

// Where adds a new predicate for the builder.
func (su *SequenceUpdate) Where(ps ...predicate.Sequence) *SequenceUpdate {
	su.predicates = append(su.predicates, ps...)
	return su
}

// SetXStart sets the X_Start field.
func (su *SequenceUpdate) SetXStart(i int) *SequenceUpdate {
	su.X_Start = &i
	su.addX_Start = nil
	return su
}

// SetNillableXStart sets the X_Start field if the given value is not nil.
func (su *SequenceUpdate) SetNillableXStart(i *int) *SequenceUpdate {
	if i != nil {
		su.SetXStart(*i)
	}
	return su
}

// AddXStart adds i to X_Start.
func (su *SequenceUpdate) AddXStart(i int) *SequenceUpdate {
	if su.addX_Start == nil {
		su.addX_Start = &i
	} else {
		*su.addX_Start += i
	}
	return su
}

// SetYStart sets the Y_Start field.
func (su *SequenceUpdate) SetYStart(i int) *SequenceUpdate {
	su.Y_Start = &i
	su.addY_Start = nil
	return su
}

// SetNillableYStart sets the Y_Start field if the given value is not nil.
func (su *SequenceUpdate) SetNillableYStart(i *int) *SequenceUpdate {
	if i != nil {
		su.SetYStart(*i)
	}
	return su
}

// AddYStart adds i to Y_Start.
func (su *SequenceUpdate) AddYStart(i int) *SequenceUpdate {
	if su.addY_Start == nil {
		su.addY_Start = &i
	} else {
		*su.addY_Start += i
	}
	return su
}

// SetXEnd sets the X_End field.
func (su *SequenceUpdate) SetXEnd(i int) *SequenceUpdate {
	su.X_End = &i
	su.addX_End = nil
	return su
}

// SetNillableXEnd sets the X_End field if the given value is not nil.
func (su *SequenceUpdate) SetNillableXEnd(i *int) *SequenceUpdate {
	if i != nil {
		su.SetXEnd(*i)
	}
	return su
}

// AddXEnd adds i to X_End.
func (su *SequenceUpdate) AddXEnd(i int) *SequenceUpdate {
	if su.addX_End == nil {
		su.addX_End = &i
	} else {
		*su.addX_End += i
	}
	return su
}

// SetYEnd sets the Y_End field.
func (su *SequenceUpdate) SetYEnd(i int) *SequenceUpdate {
	su.Y_End = &i
	su.addY_End = nil
	return su
}

// SetNillableYEnd sets the Y_End field if the given value is not nil.
func (su *SequenceUpdate) SetNillableYEnd(i *int) *SequenceUpdate {
	if i != nil {
		su.SetYEnd(*i)
	}
	return su
}

// AddYEnd adds i to Y_End.
func (su *SequenceUpdate) AddYEnd(i int) *SequenceUpdate {
	if su.addY_End == nil {
		su.addY_End = &i
	} else {
		*su.addY_End += i
	}
	return su
}

// SetDoorID sets the door edge to Door by id.
func (su *SequenceUpdate) SetDoorID(id int) *SequenceUpdate {
	if su.door == nil {
		su.door = make(map[int]struct{})
	}
	su.door[id] = struct{}{}
	return su
}

// SetNillableDoorID sets the door edge to Door by id if the given value is not nil.
func (su *SequenceUpdate) SetNillableDoorID(id *int) *SequenceUpdate {
	if id != nil {
		su = su.SetDoorID(*id)
	}
	return su
}

// SetDoor sets the door edge to Door.
func (su *SequenceUpdate) SetDoor(d *Door) *SequenceUpdate {
	return su.SetDoorID(d.ID)
}

// SetRoomID sets the room edge to Room by id.
func (su *SequenceUpdate) SetRoomID(id int) *SequenceUpdate {
	if su.room == nil {
		su.room = make(map[int]struct{})
	}
	su.room[id] = struct{}{}
	return su
}

// SetNillableRoomID sets the room edge to Room by id if the given value is not nil.
func (su *SequenceUpdate) SetNillableRoomID(id *int) *SequenceUpdate {
	if id != nil {
		su = su.SetRoomID(*id)
	}
	return su
}

// SetRoom sets the room edge to Room.
func (su *SequenceUpdate) SetRoom(r *Room) *SequenceUpdate {
	return su.SetRoomID(r.ID)
}

// ClearDoor clears the door edge to Door.
func (su *SequenceUpdate) ClearDoor() *SequenceUpdate {
	su.clearedDoor = true
	return su
}

// ClearRoom clears the room edge to Room.
func (su *SequenceUpdate) ClearRoom() *SequenceUpdate {
	su.clearedRoom = true
	return su
}

// Save executes the query and returns the number of rows/vertices matched by this operation.
func (su *SequenceUpdate) Save(ctx context.Context) (int, error) {
	if len(su.door) > 1 {
		return 0, errors.New("ent: multiple assignments on a unique edge \"door\"")
	}
	if len(su.room) > 1 {
		return 0, errors.New("ent: multiple assignments on a unique edge \"room\"")
	}
	return su.sqlSave(ctx)
}

// SaveX is like Save, but panics if an error occurs.
func (su *SequenceUpdate) SaveX(ctx context.Context) int {
	affected, err := su.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (su *SequenceUpdate) Exec(ctx context.Context) error {
	_, err := su.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (su *SequenceUpdate) ExecX(ctx context.Context) {
	if err := su.Exec(ctx); err != nil {
		panic(err)
	}
}

func (su *SequenceUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   sequence.Table,
			Columns: sequence.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: sequence.FieldID,
			},
		},
	}
	if ps := su.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value := su.X_Start; value != nil {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  *value,
			Column: sequence.FieldXStart,
		})
	}
	if value := su.addX_Start; value != nil {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  *value,
			Column: sequence.FieldXStart,
		})
	}
	if value := su.Y_Start; value != nil {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  *value,
			Column: sequence.FieldYStart,
		})
	}
	if value := su.addY_Start; value != nil {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  *value,
			Column: sequence.FieldYStart,
		})
	}
	if value := su.X_End; value != nil {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  *value,
			Column: sequence.FieldXEnd,
		})
	}
	if value := su.addX_End; value != nil {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  *value,
			Column: sequence.FieldXEnd,
		})
	}
	if value := su.Y_End; value != nil {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  *value,
			Column: sequence.FieldYEnd,
		})
	}
	if value := su.addY_End; value != nil {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  *value,
			Column: sequence.FieldYEnd,
		})
	}
	if su.clearedDoor {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   sequence.DoorTable,
			Columns: []string{sequence.DoorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: door.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.door; len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   sequence.DoorTable,
			Columns: []string{sequence.DoorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: door.FieldID,
				},
			},
		}
		for k, _ := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if su.clearedRoom {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sequence.RoomTable,
			Columns: []string{sequence.RoomColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: room.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.room; len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sequence.RoomTable,
			Columns: []string{sequence.RoomColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: room.FieldID,
				},
			},
		}
		for k, _ := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, su.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// SequenceUpdateOne is the builder for updating a single Sequence entity.
type SequenceUpdateOne struct {
	config
	id          int
	X_Start     *int
	addX_Start  *int
	Y_Start     *int
	addY_Start  *int
	X_End       *int
	addX_End    *int
	Y_End       *int
	addY_End    *int
	door        map[int]struct{}
	room        map[int]struct{}
	clearedDoor bool
	clearedRoom bool
}

// SetXStart sets the X_Start field.
func (suo *SequenceUpdateOne) SetXStart(i int) *SequenceUpdateOne {
	suo.X_Start = &i
	suo.addX_Start = nil
	return suo
}

// SetNillableXStart sets the X_Start field if the given value is not nil.
func (suo *SequenceUpdateOne) SetNillableXStart(i *int) *SequenceUpdateOne {
	if i != nil {
		suo.SetXStart(*i)
	}
	return suo
}

// AddXStart adds i to X_Start.
func (suo *SequenceUpdateOne) AddXStart(i int) *SequenceUpdateOne {
	if suo.addX_Start == nil {
		suo.addX_Start = &i
	} else {
		*suo.addX_Start += i
	}
	return suo
}

// SetYStart sets the Y_Start field.
func (suo *SequenceUpdateOne) SetYStart(i int) *SequenceUpdateOne {
	suo.Y_Start = &i
	suo.addY_Start = nil
	return suo
}

// SetNillableYStart sets the Y_Start field if the given value is not nil.
func (suo *SequenceUpdateOne) SetNillableYStart(i *int) *SequenceUpdateOne {
	if i != nil {
		suo.SetYStart(*i)
	}
	return suo
}

// AddYStart adds i to Y_Start.
func (suo *SequenceUpdateOne) AddYStart(i int) *SequenceUpdateOne {
	if suo.addY_Start == nil {
		suo.addY_Start = &i
	} else {
		*suo.addY_Start += i
	}
	return suo
}

// SetXEnd sets the X_End field.
func (suo *SequenceUpdateOne) SetXEnd(i int) *SequenceUpdateOne {
	suo.X_End = &i
	suo.addX_End = nil
	return suo
}

// SetNillableXEnd sets the X_End field if the given value is not nil.
func (suo *SequenceUpdateOne) SetNillableXEnd(i *int) *SequenceUpdateOne {
	if i != nil {
		suo.SetXEnd(*i)
	}
	return suo
}

// AddXEnd adds i to X_End.
func (suo *SequenceUpdateOne) AddXEnd(i int) *SequenceUpdateOne {
	if suo.addX_End == nil {
		suo.addX_End = &i
	} else {
		*suo.addX_End += i
	}
	return suo
}

// SetYEnd sets the Y_End field.
func (suo *SequenceUpdateOne) SetYEnd(i int) *SequenceUpdateOne {
	suo.Y_End = &i
	suo.addY_End = nil
	return suo
}

// SetNillableYEnd sets the Y_End field if the given value is not nil.
func (suo *SequenceUpdateOne) SetNillableYEnd(i *int) *SequenceUpdateOne {
	if i != nil {
		suo.SetYEnd(*i)
	}
	return suo
}

// AddYEnd adds i to Y_End.
func (suo *SequenceUpdateOne) AddYEnd(i int) *SequenceUpdateOne {
	if suo.addY_End == nil {
		suo.addY_End = &i
	} else {
		*suo.addY_End += i
	}
	return suo
}

// SetDoorID sets the door edge to Door by id.
func (suo *SequenceUpdateOne) SetDoorID(id int) *SequenceUpdateOne {
	if suo.door == nil {
		suo.door = make(map[int]struct{})
	}
	suo.door[id] = struct{}{}
	return suo
}

// SetNillableDoorID sets the door edge to Door by id if the given value is not nil.
func (suo *SequenceUpdateOne) SetNillableDoorID(id *int) *SequenceUpdateOne {
	if id != nil {
		suo = suo.SetDoorID(*id)
	}
	return suo
}

// SetDoor sets the door edge to Door.
func (suo *SequenceUpdateOne) SetDoor(d *Door) *SequenceUpdateOne {
	return suo.SetDoorID(d.ID)
}

// SetRoomID sets the room edge to Room by id.
func (suo *SequenceUpdateOne) SetRoomID(id int) *SequenceUpdateOne {
	if suo.room == nil {
		suo.room = make(map[int]struct{})
	}
	suo.room[id] = struct{}{}
	return suo
}

// SetNillableRoomID sets the room edge to Room by id if the given value is not nil.
func (suo *SequenceUpdateOne) SetNillableRoomID(id *int) *SequenceUpdateOne {
	if id != nil {
		suo = suo.SetRoomID(*id)
	}
	return suo
}

// SetRoom sets the room edge to Room.
func (suo *SequenceUpdateOne) SetRoom(r *Room) *SequenceUpdateOne {
	return suo.SetRoomID(r.ID)
}

// ClearDoor clears the door edge to Door.
func (suo *SequenceUpdateOne) ClearDoor() *SequenceUpdateOne {
	suo.clearedDoor = true
	return suo
}

// ClearRoom clears the room edge to Room.
func (suo *SequenceUpdateOne) ClearRoom() *SequenceUpdateOne {
	suo.clearedRoom = true
	return suo
}

// Save executes the query and returns the updated entity.
func (suo *SequenceUpdateOne) Save(ctx context.Context) (*Sequence, error) {
	if len(suo.door) > 1 {
		return nil, errors.New("ent: multiple assignments on a unique edge \"door\"")
	}
	if len(suo.room) > 1 {
		return nil, errors.New("ent: multiple assignments on a unique edge \"room\"")
	}
	return suo.sqlSave(ctx)
}

// SaveX is like Save, but panics if an error occurs.
func (suo *SequenceUpdateOne) SaveX(ctx context.Context) *Sequence {
	s, err := suo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return s
}

// Exec executes the query on the entity.
func (suo *SequenceUpdateOne) Exec(ctx context.Context) error {
	_, err := suo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (suo *SequenceUpdateOne) ExecX(ctx context.Context) {
	if err := suo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (suo *SequenceUpdateOne) sqlSave(ctx context.Context) (s *Sequence, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   sequence.Table,
			Columns: sequence.Columns,
			ID: &sqlgraph.FieldSpec{
				Value:  suo.id,
				Type:   field.TypeInt,
				Column: sequence.FieldID,
			},
		},
	}
	if value := suo.X_Start; value != nil {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  *value,
			Column: sequence.FieldXStart,
		})
	}
	if value := suo.addX_Start; value != nil {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  *value,
			Column: sequence.FieldXStart,
		})
	}
	if value := suo.Y_Start; value != nil {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  *value,
			Column: sequence.FieldYStart,
		})
	}
	if value := suo.addY_Start; value != nil {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  *value,
			Column: sequence.FieldYStart,
		})
	}
	if value := suo.X_End; value != nil {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  *value,
			Column: sequence.FieldXEnd,
		})
	}
	if value := suo.addX_End; value != nil {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  *value,
			Column: sequence.FieldXEnd,
		})
	}
	if value := suo.Y_End; value != nil {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  *value,
			Column: sequence.FieldYEnd,
		})
	}
	if value := suo.addY_End; value != nil {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  *value,
			Column: sequence.FieldYEnd,
		})
	}
	if suo.clearedDoor {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   sequence.DoorTable,
			Columns: []string{sequence.DoorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: door.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.door; len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   sequence.DoorTable,
			Columns: []string{sequence.DoorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: door.FieldID,
				},
			},
		}
		for k, _ := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if suo.clearedRoom {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sequence.RoomTable,
			Columns: []string{sequence.RoomColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: room.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.room; len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sequence.RoomTable,
			Columns: []string{sequence.RoomColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: room.FieldID,
				},
			},
		}
		for k, _ := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	s = &Sequence{config: suo.config}
	_spec.Assign = s.assignValues
	_spec.ScanValues = s.scanValues()
	if err = sqlgraph.UpdateNode(ctx, suo.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return s, nil
}
