// Code generated by entc, DO NOT EDIT.

package sequence

import (
	"studi-guide/ent/schema"
)

const (
	// Label holds the string label denoting the sequence type in the database.
	Label = "sequence"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldXStart holds the string denoting the x_start vertex property in the database.
	FieldXStart = "x_start"
	// FieldYStart holds the string denoting the y_start vertex property in the database.
	FieldYStart = "y_start"
	// FieldXEnd holds the string denoting the x_end vertex property in the database.
	FieldXEnd = "x_end"
	// FieldYEnd holds the string denoting the y_end vertex property in the database.
	FieldYEnd = "y_end"

	// Table holds the table name of the sequence in the database.
	Table = "sequences"
	// DoorTable is the table the holds the door relation/edge.
	DoorTable = "sequences"
	// DoorInverseTable is the table name for the Door entity.
	// It exists in this package in order to avoid circular dependency with the "door" package.
	DoorInverseTable = "doors"
	// DoorColumn is the table column denoting the door relation/edge.
	DoorColumn = "door_sequence"
	// RoomTable is the table the holds the room relation/edge.
	RoomTable = "sequences"
	// RoomInverseTable is the table name for the Room entity.
	// It exists in this package in order to avoid circular dependency with the "room" package.
	RoomInverseTable = "rooms"
	// RoomColumn is the table column denoting the room relation/edge.
	RoomColumn = "room_sequences"
)

// Columns holds all SQL columns for sequence fields.
var Columns = []string{
	FieldID,
	FieldXStart,
	FieldYStart,
	FieldXEnd,
	FieldYEnd,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the Sequence type.
var ForeignKeys = []string{
	"door_sequence",
	"room_sequences",
}

var (
	fields = schema.Sequence{}.Fields()

	// descXStart is the schema descriptor for X_Start field.
	descXStart = fields[0].Descriptor()
	// DefaultXStart holds the default value on creation for the X_Start field.
	DefaultXStart = descXStart.Default.(int)

	// descYStart is the schema descriptor for Y_Start field.
	descYStart = fields[1].Descriptor()
	// DefaultYStart holds the default value on creation for the Y_Start field.
	DefaultYStart = descYStart.Default.(int)

	// descXEnd is the schema descriptor for X_End field.
	descXEnd = fields[2].Descriptor()
	// DefaultXEnd holds the default value on creation for the X_End field.
	DefaultXEnd = descXEnd.Default.(int)

	// descYEnd is the schema descriptor for Y_End field.
	descYEnd = fields[3].Descriptor()
	// DefaultYEnd holds the default value on creation for the Y_End field.
	DefaultYEnd = descYEnd.Default.(int)
)
