// Code generated by entc, DO NOT EDIT.

package sequence

import (
	"studi-guide/ent/predicate"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their identifier.
func ID(id int) predicate.Sequence {
	return predicate.Sequence(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Sequence {
	return predicate.Sequence(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Sequence {
	return predicate.Sequence(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Sequence {
	return predicate.Sequence(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Sequence {
	return predicate.Sequence(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Sequence {
	return predicate.Sequence(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Sequence {
	return predicate.Sequence(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Sequence {
	return predicate.Sequence(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Sequence {
	return predicate.Sequence(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// XStart applies equality check predicate on the "X_Start" field. It's identical to XStartEQ.
func XStart(v int) predicate.Sequence {
	return predicate.Sequence(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldXStart), v))
	})
}

// YStart applies equality check predicate on the "Y_Start" field. It's identical to YStartEQ.
func YStart(v int) predicate.Sequence {
	return predicate.Sequence(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldYStart), v))
	})
}

// XEnd applies equality check predicate on the "X_End" field. It's identical to XEndEQ.
func XEnd(v int) predicate.Sequence {
	return predicate.Sequence(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldXEnd), v))
	})
}

// YEnd applies equality check predicate on the "Y_End" field. It's identical to YEndEQ.
func YEnd(v int) predicate.Sequence {
	return predicate.Sequence(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldYEnd), v))
	})
}

// XStartEQ applies the EQ predicate on the "X_Start" field.
func XStartEQ(v int) predicate.Sequence {
	return predicate.Sequence(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldXStart), v))
	})
}

// XStartNEQ applies the NEQ predicate on the "X_Start" field.
func XStartNEQ(v int) predicate.Sequence {
	return predicate.Sequence(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldXStart), v))
	})
}

// XStartIn applies the In predicate on the "X_Start" field.
func XStartIn(vs ...int) predicate.Sequence {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Sequence(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(vs) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldXStart), v...))
	})
}

// XStartNotIn applies the NotIn predicate on the "X_Start" field.
func XStartNotIn(vs ...int) predicate.Sequence {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Sequence(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(vs) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldXStart), v...))
	})
}

// XStartGT applies the GT predicate on the "X_Start" field.
func XStartGT(v int) predicate.Sequence {
	return predicate.Sequence(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldXStart), v))
	})
}

// XStartGTE applies the GTE predicate on the "X_Start" field.
func XStartGTE(v int) predicate.Sequence {
	return predicate.Sequence(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldXStart), v))
	})
}

// XStartLT applies the LT predicate on the "X_Start" field.
func XStartLT(v int) predicate.Sequence {
	return predicate.Sequence(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldXStart), v))
	})
}

// XStartLTE applies the LTE predicate on the "X_Start" field.
func XStartLTE(v int) predicate.Sequence {
	return predicate.Sequence(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldXStart), v))
	})
}

// YStartEQ applies the EQ predicate on the "Y_Start" field.
func YStartEQ(v int) predicate.Sequence {
	return predicate.Sequence(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldYStart), v))
	})
}

// YStartNEQ applies the NEQ predicate on the "Y_Start" field.
func YStartNEQ(v int) predicate.Sequence {
	return predicate.Sequence(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldYStart), v))
	})
}

// YStartIn applies the In predicate on the "Y_Start" field.
func YStartIn(vs ...int) predicate.Sequence {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Sequence(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(vs) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldYStart), v...))
	})
}

// YStartNotIn applies the NotIn predicate on the "Y_Start" field.
func YStartNotIn(vs ...int) predicate.Sequence {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Sequence(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(vs) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldYStart), v...))
	})
}

// YStartGT applies the GT predicate on the "Y_Start" field.
func YStartGT(v int) predicate.Sequence {
	return predicate.Sequence(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldYStart), v))
	})
}

// YStartGTE applies the GTE predicate on the "Y_Start" field.
func YStartGTE(v int) predicate.Sequence {
	return predicate.Sequence(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldYStart), v))
	})
}

// YStartLT applies the LT predicate on the "Y_Start" field.
func YStartLT(v int) predicate.Sequence {
	return predicate.Sequence(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldYStart), v))
	})
}

// YStartLTE applies the LTE predicate on the "Y_Start" field.
func YStartLTE(v int) predicate.Sequence {
	return predicate.Sequence(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldYStart), v))
	})
}

// XEndEQ applies the EQ predicate on the "X_End" field.
func XEndEQ(v int) predicate.Sequence {
	return predicate.Sequence(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldXEnd), v))
	})
}

// XEndNEQ applies the NEQ predicate on the "X_End" field.
func XEndNEQ(v int) predicate.Sequence {
	return predicate.Sequence(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldXEnd), v))
	})
}

// XEndIn applies the In predicate on the "X_End" field.
func XEndIn(vs ...int) predicate.Sequence {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Sequence(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(vs) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldXEnd), v...))
	})
}

// XEndNotIn applies the NotIn predicate on the "X_End" field.
func XEndNotIn(vs ...int) predicate.Sequence {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Sequence(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(vs) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldXEnd), v...))
	})
}

// XEndGT applies the GT predicate on the "X_End" field.
func XEndGT(v int) predicate.Sequence {
	return predicate.Sequence(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldXEnd), v))
	})
}

// XEndGTE applies the GTE predicate on the "X_End" field.
func XEndGTE(v int) predicate.Sequence {
	return predicate.Sequence(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldXEnd), v))
	})
}

// XEndLT applies the LT predicate on the "X_End" field.
func XEndLT(v int) predicate.Sequence {
	return predicate.Sequence(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldXEnd), v))
	})
}

// XEndLTE applies the LTE predicate on the "X_End" field.
func XEndLTE(v int) predicate.Sequence {
	return predicate.Sequence(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldXEnd), v))
	})
}

// YEndEQ applies the EQ predicate on the "Y_End" field.
func YEndEQ(v int) predicate.Sequence {
	return predicate.Sequence(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldYEnd), v))
	})
}

// YEndNEQ applies the NEQ predicate on the "Y_End" field.
func YEndNEQ(v int) predicate.Sequence {
	return predicate.Sequence(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldYEnd), v))
	})
}

// YEndIn applies the In predicate on the "Y_End" field.
func YEndIn(vs ...int) predicate.Sequence {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Sequence(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(vs) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldYEnd), v...))
	})
}

// YEndNotIn applies the NotIn predicate on the "Y_End" field.
func YEndNotIn(vs ...int) predicate.Sequence {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Sequence(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(vs) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldYEnd), v...))
	})
}

// YEndGT applies the GT predicate on the "Y_End" field.
func YEndGT(v int) predicate.Sequence {
	return predicate.Sequence(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldYEnd), v))
	})
}

// YEndGTE applies the GTE predicate on the "Y_End" field.
func YEndGTE(v int) predicate.Sequence {
	return predicate.Sequence(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldYEnd), v))
	})
}

// YEndLT applies the LT predicate on the "Y_End" field.
func YEndLT(v int) predicate.Sequence {
	return predicate.Sequence(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldYEnd), v))
	})
}

// YEndLTE applies the LTE predicate on the "Y_End" field.
func YEndLTE(v int) predicate.Sequence {
	return predicate.Sequence(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldYEnd), v))
	})
}

// HasDoor applies the HasEdge predicate on the "door" edge.
func HasDoor() predicate.Sequence {
	return predicate.Sequence(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(DoorTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, DoorTable, DoorColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDoorWith applies the HasEdge predicate on the "door" edge with a given conditions (other predicates).
func HasDoorWith(preds ...predicate.Door) predicate.Sequence {
	return predicate.Sequence(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(DoorInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, DoorTable, DoorColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasRoom applies the HasEdge predicate on the "room" edge.
func HasRoom() predicate.Sequence {
	return predicate.Sequence(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(RoomTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, RoomTable, RoomColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRoomWith applies the HasEdge predicate on the "room" edge with a given conditions (other predicates).
func HasRoomWith(preds ...predicate.Room) predicate.Sequence {
	return predicate.Sequence(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(RoomInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, RoomTable, RoomColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups list of predicates with the AND operator between them.
func And(predicates ...predicate.Sequence) predicate.Sequence {
	return predicate.Sequence(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups list of predicates with the OR operator between them.
func Or(predicates ...predicate.Sequence) predicate.Sequence {
	return predicate.Sequence(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Sequence) predicate.Sequence {
	return predicate.Sequence(func(s *sql.Selector) {
		p(s.Not())
	})
}
