// Code generated by entc, DO NOT EDIT.

package door

const (
	// Label holds the string label denoting the door type in the database.
	Label = "door"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldID holds the string denoting the id vertex property in the database.
	FieldID = "id"

	// Table holds the table name of the door in the database.
	Table = "doors"
	// SequenceTable is the table the holds the sequence relation/edge.
	SequenceTable = "sequences"
	// SequenceInverseTable is the table name for the Sequence entity.
	// It exists in this package in order to avoid circular dependency with the "sequence" package.
	SequenceInverseTable = "sequences"
	// SequenceColumn is the table column denoting the sequence relation/edge.
	SequenceColumn = "door_sequence"
	// PathNodesTable is the table the holds the pathNodes relation/edge.
	PathNodesTable = "path_nodes"
	// PathNodesInverseTable is the table name for the PathNode entity.
	// It exists in this package in order to avoid circular dependency with the "pathnode" package.
	PathNodesInverseTable = "path_nodes"
	// PathNodesColumn is the table column denoting the pathNodes relation/edge.
	PathNodesColumn = "door_path_nodes"
)

// Columns holds all SQL columns for door fields.
var Columns = []string{
	FieldID,
	FieldID,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the Door type.
var ForeignKeys = []string{
	"room_doors",
}
