// Code generated by entc, DO NOT EDIT.

package door

import (
	"studi-guide/ent/predicate"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their identifier.
func ID(id int) predicate.Door {
	return predicate.Door(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Door {
	return predicate.Door(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Door {
	return predicate.Door(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Door {
	return predicate.Door(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Door {
	return predicate.Door(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Door {
	return predicate.Door(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Door {
	return predicate.Door(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Door {
	return predicate.Door(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Door {
	return predicate.Door(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// HasSequence applies the HasEdge predicate on the "sequence" edge.
func HasSequence() predicate.Door {
	return predicate.Door(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(SequenceTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, SequenceTable, SequenceColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSequenceWith applies the HasEdge predicate on the "sequence" edge with a given conditions (other predicates).
func HasSequenceWith(preds ...predicate.Sequence) predicate.Door {
	return predicate.Door(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(SequenceInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, SequenceTable, SequenceColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasPathNodes applies the HasEdge predicate on the "pathNodes" edge.
func HasPathNodes() predicate.Door {
	return predicate.Door(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(PathNodesTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, PathNodesTable, PathNodesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPathNodesWith applies the HasEdge predicate on the "pathNodes" edge with a given conditions (other predicates).
func HasPathNodesWith(preds ...predicate.PathNode) predicate.Door {
	return predicate.Door(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(PathNodesInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, PathNodesTable, PathNodesColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups list of predicates with the AND operator between them.
func And(predicates ...predicate.Door) predicate.Door {
	return predicate.Door(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups list of predicates with the OR operator between them.
func Or(predicates ...predicate.Door) predicate.Door {
	return predicate.Door(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Door) predicate.Door {
	return predicate.Door(func(s *sql.Selector) {
		p(s.Not())
	})
}
