// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"studi-guide/ent/pathnode"
	"studi-guide/ent/room"
	"studi-guide/ent/sequence"

	"github.com/facebookincubator/ent/dialect/sql/schema"
	"github.com/facebookincubator/ent/schema/field"
)

var (
	// DoorsColumns holds the columns for the "doors" table.
	DoorsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "id", Type: field.TypeInt, Unique: true},
		{Name: "room_doors", Type: field.TypeInt, Nullable: true},
	}
	// DoorsTable holds the schema information for the "doors" table.
	DoorsTable = &schema.Table{
		Name:       "doors",
		Columns:    DoorsColumns,
		PrimaryKey: []*schema.Column{DoorsColumns[0], DoorsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:  "doors_rooms_doors",
				Columns: []*schema.Column{DoorsColumns[2]},

				RefColumns: []*schema.Column{RoomsColumns[0], RoomsColumns[4]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// PathNodesColumns holds the columns for the "path_nodes" table.
	PathNodesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "id", Type: field.TypeInt, Unique: true},
		{Name: "x_coordinate", Type: field.TypeInt, Default: pathnode.DefaultXCoordinate},
		{Name: "y_coordinate", Type: field.TypeInt, Default: pathnode.DefaultYCoordinate},
		{Name: "floor", Type: field.TypeInt, Default: pathnode.DefaultFloor},
		{Name: "door_path_nodes", Type: field.TypeInt, Unique: true, Nullable: true},
		{Name: "room_path_nodes", Type: field.TypeInt, Nullable: true},
	}
	// PathNodesTable holds the schema information for the "path_nodes" table.
	PathNodesTable = &schema.Table{
		Name:       "path_nodes",
		Columns:    PathNodesColumns,
		PrimaryKey: []*schema.Column{PathNodesColumns[0], PathNodesColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:  "path_nodes_doors_pathNodes",
				Columns: []*schema.Column{PathNodesColumns[5]},

				RefColumns: []*schema.Column{DoorsColumns[0], DoorsColumns[1]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:  "path_nodes_rooms_pathNodes",
				Columns: []*schema.Column{PathNodesColumns[6]},

				RefColumns: []*schema.Column{RoomsColumns[0], RoomsColumns[4]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// RoomsColumns holds the columns for the "rooms" table.
	RoomsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Default: room.DefaultDescription},
		{Name: "floor", Type: field.TypeInt, Default: room.DefaultFloor},
		{Name: "id", Type: field.TypeInt},
	}
	// RoomsTable holds the schema information for the "rooms" table.
	RoomsTable = &schema.Table{
		Name:        "rooms",
		Columns:     RoomsColumns,
		PrimaryKey:  []*schema.Column{RoomsColumns[0], RoomsColumns[4]},
		ForeignKeys: []*schema.ForeignKey{},
		Indexes: []*schema.Index{
			{
				Name:    "room_id_name",
				Unique:  true,
				Columns: []*schema.Column{RoomsColumns[0], RoomsColumns[4], RoomsColumns[1]},
			},
		},
	}
	// SequencesColumns holds the columns for the "sequences" table.
	SequencesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "x_start", Type: field.TypeInt, Default: sequence.DefaultXStart},
		{Name: "y_start", Type: field.TypeInt, Default: sequence.DefaultYStart},
		{Name: "x_end", Type: field.TypeInt, Default: sequence.DefaultXEnd},
		{Name: "y_end", Type: field.TypeInt, Default: sequence.DefaultYEnd},
		{Name: "id", Type: field.TypeInt, Unique: true},
		{Name: "door_sequence", Type: field.TypeInt, Unique: true, Nullable: true},
		{Name: "room_sequences", Type: field.TypeInt, Nullable: true},
	}
	// SequencesTable holds the schema information for the "sequences" table.
	SequencesTable = &schema.Table{
		Name:       "sequences",
		Columns:    SequencesColumns,
		PrimaryKey: []*schema.Column{SequencesColumns[0], SequencesColumns[5]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:  "sequences_doors_sequence",
				Columns: []*schema.Column{SequencesColumns[6]},

				RefColumns: []*schema.Column{DoorsColumns[0], DoorsColumns[1]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:  "sequences_rooms_sequences",
				Columns: []*schema.Column{SequencesColumns[7]},

				RefColumns: []*schema.Column{RoomsColumns[0], RoomsColumns[4]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// PathNodeLinkedToColumns holds the columns for the "path_node_linkedTo" table.
	PathNodeLinkedToColumns = []*schema.Column{
		{Name: "path_node_id", Type: field.TypeInt},
		{Name: "linkedFrom_id", Type: field.TypeInt},
	}
	// PathNodeLinkedToTable holds the schema information for the "path_node_linkedTo" table.
	PathNodeLinkedToTable = &schema.Table{
		Name:       "path_node_linkedTo",
		Columns:    PathNodeLinkedToColumns,
		PrimaryKey: []*schema.Column{PathNodeLinkedToColumns[0], PathNodeLinkedToColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:  "path_node_linkedTo_path_node_id",
				Columns: []*schema.Column{PathNodeLinkedToColumns[0]},

				RefColumns: []*schema.Column{PathNodesColumns[0], PathNodesColumns[1]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:  "path_node_linkedTo_linkedFrom_id",
				Columns: []*schema.Column{PathNodeLinkedToColumns[1]},

				RefColumns: []*schema.Column{PathNodesColumns[0], PathNodesColumns[1]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		DoorsTable,
		PathNodesTable,
		RoomsTable,
		SequencesTable,
		PathNodeLinkedToTable,
	}
)

func init() {
	DoorsTable.ForeignKeys[0].RefTable = RoomsTable
	PathNodesTable.ForeignKeys[0].RefTable = DoorsTable
	PathNodesTable.ForeignKeys[1].RefTable = RoomsTable
	SequencesTable.ForeignKeys[0].RefTable = DoorsTable
	SequencesTable.ForeignKeys[1].RefTable = RoomsTable
	PathNodeLinkedToTable.ForeignKeys[0].RefTable = PathNodesTable
	PathNodeLinkedToTable.ForeignKeys[1].RefTable = PathNodesTable
}
