// Code generated by entc, DO NOT EDIT.

package pathnode

import (
	"studi-guide/ent/schema"
)

const (
	// Label holds the string label denoting the pathnode type in the database.
	Label = "path_node"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldID holds the string denoting the id vertex property in the database.
	FieldID = "id"
	// FieldXCoordinate holds the string denoting the x_coordinate vertex property in the database.
	FieldXCoordinate = "x_coordinate"
	// FieldYCoordinate holds the string denoting the y_coordinate vertex property in the database.
	FieldYCoordinate = "y_coordinate"
	// FieldFloor holds the string denoting the floor vertex property in the database.
	FieldFloor = "floor"

	// Table holds the table name of the pathnode in the database.
	Table = "path_nodes"
	// DoorTable is the table the holds the door relation/edge.
	DoorTable = "path_nodes"
	// DoorInverseTable is the table name for the Door entity.
	// It exists in this package in order to avoid circular dependency with the "door" package.
	DoorInverseTable = "doors"
	// DoorColumn is the table column denoting the door relation/edge.
	DoorColumn = "door_path_nodes"
	// RoomTable is the table the holds the room relation/edge.
	RoomTable = "path_nodes"
	// RoomInverseTable is the table name for the Room entity.
	// It exists in this package in order to avoid circular dependency with the "room" package.
	RoomInverseTable = "rooms"
	// RoomColumn is the table column denoting the room relation/edge.
	RoomColumn = "room_path_nodes"
	// LinkedFromTable is the table the holds the linkedFrom relation/edge. The primary key declared below.
	LinkedFromTable = "path_node_linkedTo"
	// LinkedToTable is the table the holds the linkedTo relation/edge. The primary key declared below.
	LinkedToTable = "path_node_linkedTo"
)

// Columns holds all SQL columns for pathnode fields.
var Columns = []string{
	FieldID,
	FieldID,
	FieldXCoordinate,
	FieldYCoordinate,
	FieldFloor,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the PathNode type.
var ForeignKeys = []string{
	"door_path_nodes",
	"room_path_nodes",
}

var (
	// LinkedFromPrimaryKey and LinkedFromColumn2 are the table columns denoting the
	// primary key for the linkedFrom relation (M2M).
	LinkedFromPrimaryKey = []string{"path_node_id", "linkedFrom_id"}
	// LinkedToPrimaryKey and LinkedToColumn2 are the table columns denoting the
	// primary key for the linkedTo relation (M2M).
	LinkedToPrimaryKey = []string{"path_node_id", "linkedFrom_id"}
)

var (
	fields = schema.PathNode{}.Fields()

	// descXCoordinate is the schema descriptor for X_Coordinate field.
	descXCoordinate = fields[1].Descriptor()
	// DefaultXCoordinate holds the default value on creation for the X_Coordinate field.
	DefaultXCoordinate = descXCoordinate.Default.(int)

	// descYCoordinate is the schema descriptor for Y_Coordinate field.
	descYCoordinate = fields[2].Descriptor()
	// DefaultYCoordinate holds the default value on creation for the Y_Coordinate field.
	DefaultYCoordinate = descYCoordinate.Default.(int)

	// descFloor is the schema descriptor for Floor field.
	descFloor = fields[3].Descriptor()
	// DefaultFloor holds the default value on creation for the Floor field.
	DefaultFloor = descFloor.Default.(int)
)
