// Code generated by entc, DO NOT EDIT.

package pathnode

import (
	"studi-guide/ent/predicate"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their identifier.
func ID(id int) predicate.PathNode {
	return predicate.PathNode(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.PathNode {
	return predicate.PathNode(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.PathNode {
	return predicate.PathNode(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.PathNode {
	return predicate.PathNode(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.PathNode {
	return predicate.PathNode(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.PathNode {
	return predicate.PathNode(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.PathNode {
	return predicate.PathNode(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.PathNode {
	return predicate.PathNode(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.PathNode {
	return predicate.PathNode(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// XCoordinate applies equality check predicate on the "X_Coordinate" field. It's identical to XCoordinateEQ.
func XCoordinate(v int) predicate.PathNode {
	return predicate.PathNode(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldXCoordinate), v))
	})
}

// YCoordinate applies equality check predicate on the "Y_Coordinate" field. It's identical to YCoordinateEQ.
func YCoordinate(v int) predicate.PathNode {
	return predicate.PathNode(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldYCoordinate), v))
	})
}

// Floor applies equality check predicate on the "Floor" field. It's identical to FloorEQ.
func Floor(v int) predicate.PathNode {
	return predicate.PathNode(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldFloor), v))
	})
}

// XCoordinateEQ applies the EQ predicate on the "X_Coordinate" field.
func XCoordinateEQ(v int) predicate.PathNode {
	return predicate.PathNode(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldXCoordinate), v))
	})
}

// XCoordinateNEQ applies the NEQ predicate on the "X_Coordinate" field.
func XCoordinateNEQ(v int) predicate.PathNode {
	return predicate.PathNode(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldXCoordinate), v))
	})
}

// XCoordinateIn applies the In predicate on the "X_Coordinate" field.
func XCoordinateIn(vs ...int) predicate.PathNode {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.PathNode(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(vs) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldXCoordinate), v...))
	})
}

// XCoordinateNotIn applies the NotIn predicate on the "X_Coordinate" field.
func XCoordinateNotIn(vs ...int) predicate.PathNode {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.PathNode(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(vs) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldXCoordinate), v...))
	})
}

// XCoordinateGT applies the GT predicate on the "X_Coordinate" field.
func XCoordinateGT(v int) predicate.PathNode {
	return predicate.PathNode(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldXCoordinate), v))
	})
}

// XCoordinateGTE applies the GTE predicate on the "X_Coordinate" field.
func XCoordinateGTE(v int) predicate.PathNode {
	return predicate.PathNode(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldXCoordinate), v))
	})
}

// XCoordinateLT applies the LT predicate on the "X_Coordinate" field.
func XCoordinateLT(v int) predicate.PathNode {
	return predicate.PathNode(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldXCoordinate), v))
	})
}

// XCoordinateLTE applies the LTE predicate on the "X_Coordinate" field.
func XCoordinateLTE(v int) predicate.PathNode {
	return predicate.PathNode(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldXCoordinate), v))
	})
}

// YCoordinateEQ applies the EQ predicate on the "Y_Coordinate" field.
func YCoordinateEQ(v int) predicate.PathNode {
	return predicate.PathNode(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldYCoordinate), v))
	})
}

// YCoordinateNEQ applies the NEQ predicate on the "Y_Coordinate" field.
func YCoordinateNEQ(v int) predicate.PathNode {
	return predicate.PathNode(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldYCoordinate), v))
	})
}

// YCoordinateIn applies the In predicate on the "Y_Coordinate" field.
func YCoordinateIn(vs ...int) predicate.PathNode {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.PathNode(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(vs) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldYCoordinate), v...))
	})
}

// YCoordinateNotIn applies the NotIn predicate on the "Y_Coordinate" field.
func YCoordinateNotIn(vs ...int) predicate.PathNode {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.PathNode(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(vs) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldYCoordinate), v...))
	})
}

// YCoordinateGT applies the GT predicate on the "Y_Coordinate" field.
func YCoordinateGT(v int) predicate.PathNode {
	return predicate.PathNode(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldYCoordinate), v))
	})
}

// YCoordinateGTE applies the GTE predicate on the "Y_Coordinate" field.
func YCoordinateGTE(v int) predicate.PathNode {
	return predicate.PathNode(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldYCoordinate), v))
	})
}

// YCoordinateLT applies the LT predicate on the "Y_Coordinate" field.
func YCoordinateLT(v int) predicate.PathNode {
	return predicate.PathNode(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldYCoordinate), v))
	})
}

// YCoordinateLTE applies the LTE predicate on the "Y_Coordinate" field.
func YCoordinateLTE(v int) predicate.PathNode {
	return predicate.PathNode(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldYCoordinate), v))
	})
}

// FloorEQ applies the EQ predicate on the "Floor" field.
func FloorEQ(v int) predicate.PathNode {
	return predicate.PathNode(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldFloor), v))
	})
}

// FloorNEQ applies the NEQ predicate on the "Floor" field.
func FloorNEQ(v int) predicate.PathNode {
	return predicate.PathNode(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldFloor), v))
	})
}

// FloorIn applies the In predicate on the "Floor" field.
func FloorIn(vs ...int) predicate.PathNode {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.PathNode(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(vs) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldFloor), v...))
	})
}

// FloorNotIn applies the NotIn predicate on the "Floor" field.
func FloorNotIn(vs ...int) predicate.PathNode {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.PathNode(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(vs) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldFloor), v...))
	})
}

// FloorGT applies the GT predicate on the "Floor" field.
func FloorGT(v int) predicate.PathNode {
	return predicate.PathNode(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldFloor), v))
	})
}

// FloorGTE applies the GTE predicate on the "Floor" field.
func FloorGTE(v int) predicate.PathNode {
	return predicate.PathNode(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldFloor), v))
	})
}

// FloorLT applies the LT predicate on the "Floor" field.
func FloorLT(v int) predicate.PathNode {
	return predicate.PathNode(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldFloor), v))
	})
}

// FloorLTE applies the LTE predicate on the "Floor" field.
func FloorLTE(v int) predicate.PathNode {
	return predicate.PathNode(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldFloor), v))
	})
}

// HasDoor applies the HasEdge predicate on the "door" edge.
func HasDoor() predicate.PathNode {
	return predicate.PathNode(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(DoorTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, DoorTable, DoorColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDoorWith applies the HasEdge predicate on the "door" edge with a given conditions (other predicates).
func HasDoorWith(preds ...predicate.Door) predicate.PathNode {
	return predicate.PathNode(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(DoorInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, DoorTable, DoorColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasRoom applies the HasEdge predicate on the "room" edge.
func HasRoom() predicate.PathNode {
	return predicate.PathNode(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(RoomTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, RoomTable, RoomColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRoomWith applies the HasEdge predicate on the "room" edge with a given conditions (other predicates).
func HasRoomWith(preds ...predicate.Room) predicate.PathNode {
	return predicate.PathNode(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(RoomInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, RoomTable, RoomColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasLinkedFrom applies the HasEdge predicate on the "linkedFrom" edge.
func HasLinkedFrom() predicate.PathNode {
	return predicate.PathNode(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(LinkedFromTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, LinkedFromTable, LinkedFromPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasLinkedFromWith applies the HasEdge predicate on the "linkedFrom" edge with a given conditions (other predicates).
func HasLinkedFromWith(preds ...predicate.PathNode) predicate.PathNode {
	return predicate.PathNode(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, LinkedFromTable, LinkedFromPrimaryKey...),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasLinkedTo applies the HasEdge predicate on the "linkedTo" edge.
func HasLinkedTo() predicate.PathNode {
	return predicate.PathNode(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(LinkedToTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, LinkedToTable, LinkedToPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasLinkedToWith applies the HasEdge predicate on the "linkedTo" edge with a given conditions (other predicates).
func HasLinkedToWith(preds ...predicate.PathNode) predicate.PathNode {
	return predicate.PathNode(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, LinkedToTable, LinkedToPrimaryKey...),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups list of predicates with the AND operator between them.
func And(predicates ...predicate.PathNode) predicate.PathNode {
	return predicate.PathNode(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups list of predicates with the OR operator between them.
func Or(predicates ...predicate.PathNode) predicate.PathNode {
	return predicate.PathNode(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PathNode) predicate.PathNode {
	return predicate.PathNode(func(s *sql.Selector) {
		p(s.Not())
	})
}
